# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QRegExp
from PyQt5.QtGui import QRegExpValidator
from PyQt5.QtWidgets import QLineEdit, QMenu

from assets.python import qss_reader


class UiMainWindow(QtWidgets.QMainWindow):

    def __init__(self, main_window):
        super().__init__()
        style_file = './assets/qss/darkstyle.qss'
        self.qss_style = qss_reader.QssReader.read_qss(style_file)
        main_window.setStyleSheet(self.qss_style)
        self.setup_ui(main_window)

    def setup_ui(self, main_window):
        main_window.setObjectName("MainWindow")
        main_window.resize(812, 600)
        main_window.setFixedSize(main_window.width(), main_window.height());
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.switch_sd = QtWidgets.QStackedWidget(self.centralwidget)
        self.switch_sd.setGeometry(QtCore.QRect(10, 10, 791, 551))
        self.switch_sd.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.switch_sd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.switch_sd.setObjectName("switch_sd")
        self.single = QtWidgets.QWidget()
        self.single.setObjectName("single")
        self.cipher_switch_toolbox = QtWidgets.QToolBox(self.single)
        self.cipher_switch_toolbox.setGeometry(QtCore.QRect(10, 10, 151, 541))
        self.cipher_switch_toolbox.setFrameShape(QtWidgets.QFrame.Panel)
        self.cipher_switch_toolbox.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cipher_switch_toolbox.setObjectName("cipher_switch_toolbox")
        self.gudianmima = QtWidgets.QWidget()
        self.gudianmima.setGeometry(QtCore.QRect(0, 0, 149, 359))
        self.gudianmima.setObjectName("gudianmima")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gudianmima)
        self.verticalLayout.setObjectName("verticalLayout")
        self.classical_cipher_switch = QtWidgets.QToolBox(self.gudianmima)
        self.classical_cipher_switch.setFrameShape(QtWidgets.QFrame.Panel)
        self.classical_cipher_switch.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.classical_cipher_switch.setObjectName("classical_cipher_switch")
        self.danbiaotidai = QtWidgets.QWidget()
        self.danbiaotidai.setGeometry(QtCore.QRect(0, 0, 125, 215))
        self.danbiaotidai.setObjectName("danbiaotidai")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.danbiaotidai)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.kaisa = QtWidgets.QPushButton(self.danbiaotidai)
        self.kaisa.setCheckable(True)
        self.kaisa.setChecked(False)
        self.kaisa.setDefault(True)
        self.kaisa.setFlat(True)
        self.kaisa.setObjectName("kaisa")
        self.button_group = QtWidgets.QButtonGroup(main_window)
        self.button_group.setObjectName("button_group")
        self.button_group.addButton(self.kaisa)
        self.verticalLayout_4.addWidget(self.kaisa)
        self.guanjianzi = QtWidgets.QPushButton(self.danbiaotidai)
        self.guanjianzi.setCheckable(True)
        self.guanjianzi.setFlat(True)
        self.guanjianzi.setObjectName("guanjianzi")
        self.button_group.addButton(self.guanjianzi)
        self.verticalLayout_4.addWidget(self.guanjianzi)
        self.fangshe = QtWidgets.QPushButton(self.danbiaotidai)
        self.fangshe.setCheckable(True)
        self.fangshe.setFlat(True)
        self.fangshe.setObjectName("fangshe")
        self.button_group.addButton(self.fangshe)
        self.verticalLayout_4.addWidget(self.fangshe)
        self.duobian = QtWidgets.QPushButton(self.danbiaotidai)
        self.duobian.setCheckable(True)
        self.duobian.setFlat(True)
        self.duobian.setObjectName("duobian")
        self.button_group.addButton(self.duobian)
        self.verticalLayout_4.addWidget(self.duobian)
        self.classical_cipher_switch.addItem(self.danbiaotidai, "")
        self.duobiaotidai = QtWidgets.QWidget()
        self.duobiaotidai.setGeometry(QtCore.QRect(0, 0, 125, 215))
        self.duobiaotidai.setObjectName("duobiaotidai")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.duobiaotidai)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.weijiniya = QtWidgets.QPushButton(self.duobiaotidai)
        self.weijiniya.setCheckable(True)
        self.weijiniya.setDefault(True)
        self.weijiniya.setFlat(True)
        self.weijiniya.setObjectName("weijiniya")
        self.button_group.addButton(self.weijiniya)
        self.verticalLayout_5.addWidget(self.weijiniya)
        self.autokeymi = QtWidgets.QPushButton(self.duobiaotidai)
        self.autokeymi.setCheckable(True)
        self.autokeymi.setFlat(True)
        self.autokeymi.setObjectName("autokeymi")
        self.button_group.addButton(self.autokeymi)
        self.verticalLayout_5.addWidget(self.autokeymi)
        self.autokeyming = QtWidgets.QPushButton(self.duobiaotidai)
        self.autokeyming.setCheckable(True)
        self.autokeyming.setFlat(True)
        self.autokeyming.setObjectName("autokeyming")
        self.button_group.addButton(self.autokeyming)
        self.verticalLayout_5.addWidget(self.autokeyming)
        self.classical_cipher_switch.addItem(self.duobiaotidai, "")
        self.duotutidai = QtWidgets.QWidget()
        self.duotutidai.setGeometry(QtCore.QRect(0, 0, 125, 215))
        self.duotutidai.setObjectName("duotutidai")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.duotutidai)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.boleifei = QtWidgets.QPushButton(self.duotutidai)
        self.boleifei.setCheckable(True)
        self.boleifei.setDefault(True)
        self.boleifei.setFlat(True)
        self.boleifei.setObjectName("boleifei")
        self.button_group.addButton(self.boleifei)
        self.verticalLayout_6.addWidget(self.boleifei)
        self.classical_cipher_switch.addItem(self.duotutidai, "")
        self.zhihuan_2 = QtWidgets.QWidget()
        self.zhihuan_2.setGeometry(QtCore.QRect(0, 0, 125, 215))
        self.zhihuan_2.setObjectName("zhihuan_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.zhihuan_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.zhihuan = QtWidgets.QPushButton(self.zhihuan_2)
        self.zhihuan.setCheckable(True)
        self.zhihuan.setDefault(True)
        self.zhihuan.setFlat(True)
        self.zhihuan.setObjectName("zhihuan")
        self.button_group.addButton(self.zhihuan)
        self.verticalLayout_7.addWidget(self.zhihuan)
        self.liezhihuan = QtWidgets.QPushButton(self.zhihuan_2)
        self.liezhihuan.setCheckable(True)
        self.liezhihuan.setFlat(True)
        self.liezhihuan.setObjectName("liezhihuan")
        self.button_group.addButton(self.liezhihuan)
        self.verticalLayout_7.addWidget(self.liezhihuan)
        self.shuangchongzhihuan = QtWidgets.QPushButton(self.zhihuan_2)
        self.shuangchongzhihuan.setCheckable(True)
        self.shuangchongzhihuan.setFlat(True)
        self.shuangchongzhihuan.setObjectName("shuangchongzhihuan")
        self.button_group.addButton(self.shuangchongzhihuan)
        self.verticalLayout_7.addWidget(self.shuangchongzhihuan)
        self.classical_cipher_switch.addItem(self.zhihuan_2, "")
        self.verticalLayout.addWidget(self.classical_cipher_switch)
        self.cipher_switch_toolbox.addItem(self.gudianmima, "")
        self.liumima = QtWidgets.QWidget()
        self.liumima.setGeometry(QtCore.QRect(0, 0, 149, 359))
        self.liumima.setObjectName("liumima")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.liumima)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.RC4 = QtWidgets.QPushButton(self.liumima)
        self.RC4.setCheckable(True)
        self.RC4.setAutoDefault(False)
        self.RC4.setDefault(True)
        self.RC4.setFlat(True)
        self.RC4.setObjectName("RC4")
        self.button_group.addButton(self.RC4)
        self.verticalLayout_8.addWidget(self.RC4)
        self.CA = QtWidgets.QPushButton(self.liumima)
        self.CA.setCheckable(True)
        self.CA.setDefault(False)
        self.CA.setFlat(True)
        self.CA.setObjectName("CA")
        self.button_group.addButton(self.CA)
        self.verticalLayout_8.addWidget(self.CA)
        self.cipher_switch_toolbox.addItem(self.liumima, "")
        self.fenzumima = QtWidgets.QWidget()
        self.fenzumima.setGeometry(QtCore.QRect(0, 0, 149, 359))
        self.fenzumima.setObjectName("fenzumima")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.fenzumima)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.DES = QtWidgets.QPushButton(self.fenzumima)
        self.DES.setCheckable(True)
        self.DES.setDefault(True)
        self.DES.setFlat(True)
        self.DES.setObjectName("DES")
        self.button_group.addButton(self.DES)
        self.verticalLayout_2.addWidget(self.DES)
        self.AES = QtWidgets.QPushButton(self.fenzumima)
        self.AES.setCheckable(True)
        self.AES.setFlat(True)
        self.AES.setObjectName("aes")
        self.button_group.addButton(self.AES)
        self.verticalLayout_2.addWidget(self.AES)
        self.cipher_switch_toolbox.addItem(self.fenzumima, "")
        self.gongyaomima = QtWidgets.QWidget()
        self.gongyaomima.setGeometry(QtCore.QRect(0, 0, 149, 359))
        self.gongyaomima.setObjectName("gongyaomima")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.gongyaomima)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.RSA = QtWidgets.QPushButton(self.gongyaomima)
        self.RSA.setCheckable(True)
        self.RSA.setFlat(True)
        self.RSA.setObjectName("RSA")
        self.button_group.addButton(self.RSA)
        self.verticalLayout_3.addWidget(self.RSA)
        self.ECC = QtWidgets.QPushButton(self.gongyaomima)
        self.ECC.setCheckable(True)
        self.ECC.setFlat(True)
        self.ECC.setObjectName("ECC")
        self.button_group.addButton(self.ECC)
        self.verticalLayout_3.addWidget(self.ECC)
        self.cipher_switch_toolbox.addItem(self.gongyaomima, "")
        self.danxiangsanlie = QtWidgets.QWidget()
        self.danxiangsanlie.setGeometry(QtCore.QRect(0, 0, 149, 359))
        self.danxiangsanlie.setObjectName("danxiangsanlie")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.danxiangsanlie)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.MD5 = QtWidgets.QPushButton(self.danxiangsanlie)
        self.MD5.setCheckable(True)
        self.MD5.setFlat(True)
        self.MD5.setObjectName("MD5")
        self.button_group.addButton(self.MD5)
        self.verticalLayout_9.addWidget(self.MD5)
        self.cipher_switch_toolbox.addItem(self.danxiangsanlie, "")
        self.guanyu = QtWidgets.QWidget()
        self.guanyu.setGeometry(QtCore.QRect(0, 0, 149, 359))
        self.guanyu.setObjectName("guanyu")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.guanyu)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.about = QtWidgets.QTextBrowser(self.guanyu)
        self.about.setFrameShape(QtWidgets.QFrame.Panel)
        self.about.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.about.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.about.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.about.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.about.setOpenExternalLinks(False)
        self.about.setObjectName("about")
        self.horizontalLayout.addWidget(self.about)
        self.cipher_switch_toolbox.addItem(self.guanyu, "")
        self.cipher_with_key_frame = QtWidgets.QFrame(self.single)
        self.cipher_with_key_frame.setGeometry(QtCore.QRect(170, 10, 591, 541))
        self.cipher_with_key_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.cipher_with_key_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cipher_with_key_frame.setObjectName("cipher_with_key_frame")
        self.input_label = QtWidgets.QLabel(self.cipher_with_key_frame)
        self.input_label.setGeometry(QtCore.QRect(20, 20, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.input_label.setFont(font)
        self.input_label.setTextFormat(QtCore.Qt.AutoText)
        self.input_label.setWordWrap(False)
        self.input_label.setObjectName("input_label")
        self.input_key = QtWidgets.QLineEdit(self.cipher_with_key_frame)
        self.input_key.setGeometry(QtCore.QRect(110, 20, 391, 31))
        self.input_key.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.input_key.setClearButtonEnabled(False)
        self.input_key.setObjectName("input_key")
        self.ie_key_tool_button = QtWidgets.QToolButton(self.cipher_with_key_frame)
        self.ie_key_tool_button.setGeometry(QtCore.QRect(510, 20, 61, 31))
        self.ie_key_tool_button.setObjectName("ie_key_tool_button")
        self.progress_bar = QtWidgets.QProgressBar(self.cipher_with_key_frame)
        self.progress_bar.setGeometry(QtCore.QRect(20, 500, 551, 23))
        self.progress_bar.setProperty("value", 24)
        self.progress_bar.setObjectName("progress_bar")
        self.cipher_text_edit = QtWidgets.QPlainTextEdit(self.cipher_with_key_frame)
        self.cipher_text_edit.setGeometry(QtCore.QRect(330, 100, 241, 381))
        self.cipher_text_edit.setFrameShape(QtWidgets.QFrame.Box)
        self.cipher_text_edit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cipher_text_edit.setObjectName("cipher_text_edit")
        self.plain_text_edit = QtWidgets.QPlainTextEdit(self.cipher_with_key_frame)
        self.plain_text_edit.setGeometry(QtCore.QRect(20, 100, 231, 381))
        self.plain_text_edit.setFrameShape(QtWidgets.QFrame.Box)
        self.plain_text_edit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plain_text_edit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plain_text_edit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.plain_text_edit.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.plain_text_edit.setObjectName("plain_text_edit")
        self.plaintext_label = QtWidgets.QLabel(self.cipher_with_key_frame)
        self.plaintext_label.setGeometry(QtCore.QRect(30, 60, 51, 31))
        self.plaintext_label.setObjectName("plaintext_label")
        self.import_plaintext_button = QtWidgets.QPushButton(self.cipher_with_key_frame)
        self.import_plaintext_button.setGeometry(QtCore.QRect(190, 60, 61, 31))
        self.import_plaintext_button.setObjectName("import_plaintext_button")
        self.export_ciphertext_button = QtWidgets.QPushButton(self.cipher_with_key_frame)
        self.export_ciphertext_button.setGeometry(QtCore.QRect(510, 60, 61, 31))
        self.export_ciphertext_button.setObjectName("export_ciphertext_button")
        self.ciphertext_label = QtWidgets.QLabel(self.cipher_with_key_frame)
        self.ciphertext_label.setGeometry(QtCore.QRect(340, 60, 51, 31))
        self.ciphertext_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ciphertext_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ciphertext_label.setObjectName("ciphertext_label")
        self.encrypt_button = QtWidgets.QPushButton(self.cipher_with_key_frame)
        self.encrypt_button.setGeometry(QtCore.QRect(262, 210, 61, 31))
        self.encrypt_button.setObjectName("encrypt_button")
        self.decrypt_button = QtWidgets.QPushButton(self.cipher_with_key_frame)
        self.decrypt_button.setGeometry(QtCore.QRect(260, 350, 61, 31))
        self.decrypt_button.setObjectName("decrypt_button")
        self.arrow_right = QtWidgets.QLabel(self.cipher_with_key_frame)
        self.arrow_right.setGeometry(QtCore.QRect(251, 260, 81, 20))
        self.arrow_right.setObjectName("arrow_right")
        self.arrow_left = QtWidgets.QLabel(self.cipher_with_key_frame)
        self.arrow_left.setGeometry(QtCore.QRect(251, 310, 81, 20))
        self.arrow_left.setObjectName("arrow_left")
        self.check_key = QtWidgets.QCheckBox(self.cipher_with_key_frame)
        self.check_key.setGeometry(QtCore.QRect(410, 26, 91, 20))
        self.check_key.setObjectName("check_key")
        self.label = QtWidgets.QLabel(self.cipher_with_key_frame)
        self.label.setGeometry(QtCore.QRect(250, 285, 81, 21))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.switch_mode_with_key_tabwidget = QtWidgets.QTabWidget(self.single)
        self.switch_mode_with_key_tabwidget.setEnabled(True)
        self.switch_mode_with_key_tabwidget.setGeometry(QtCore.QRect(170, 10, 591, 541))
        self.switch_mode_with_key_tabwidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.switch_mode_with_key_tabwidget.setAcceptDrops(False)
        self.switch_mode_with_key_tabwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.switch_mode_with_key_tabwidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.switch_mode_with_key_tabwidget.setObjectName("switch_mode_with_key_tabwidget")
        self.str_tab = QtWidgets.QWidget()
        self.str_tab.setObjectName("str_tab")
        self.ie_key_tool_button_2 = QtWidgets.QToolButton(self.str_tab)
        self.ie_key_tool_button_2.setGeometry(QtCore.QRect(510, 10, 61, 31))
        self.ie_key_tool_button_2.setObjectName("ie_key_tool_button_2")
        self.plaintext_label_2 = QtWidgets.QLabel(self.str_tab)
        self.plaintext_label_2.setGeometry(QtCore.QRect(29, 50, 51, 31))
        self.plaintext_label_2.setObjectName("plaintext_label_2")
        self.input_key_2 = QtWidgets.QLineEdit(self.str_tab)
        self.input_key_2.setGeometry(QtCore.QRect(110, 10, 391, 31))
        self.input_key_2.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.input_key_2.setClearButtonEnabled(False)
        self.input_key_2.setObjectName("input_key_2")
        self.import_plaintext_button_2 = QtWidgets.QPushButton(self.str_tab)
        self.import_plaintext_button_2.setGeometry(QtCore.QRect(189, 50, 61, 31))
        self.import_plaintext_button_2.setObjectName("import_plaintext_button_2")
        self.check_key_2 = QtWidgets.QCheckBox(self.str_tab)
        self.check_key_2.setGeometry(QtCore.QRect(410, 16, 91, 20))
        self.check_key_2.setObjectName("check_key_2")
        self.cipher_text_edit_2 = QtWidgets.QPlainTextEdit(self.str_tab)
        self.cipher_text_edit_2.setGeometry(QtCore.QRect(329, 90, 241, 381))
        self.cipher_text_edit_2.setFrameShape(QtWidgets.QFrame.Box)
        self.cipher_text_edit_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cipher_text_edit_2.setObjectName("cipher_text_edit_2")
        self.progress_bar_2 = QtWidgets.QProgressBar(self.str_tab)
        self.progress_bar_2.setGeometry(QtCore.QRect(20, 480, 551, 23))
        self.progress_bar_2.setProperty("value", 24)
        self.progress_bar_2.setObjectName("progress_bar_2")
        self.decrypt_button_2 = QtWidgets.QPushButton(self.str_tab)
        self.decrypt_button_2.setGeometry(QtCore.QRect(259, 340, 61, 31))
        self.decrypt_button_2.setObjectName("decrypt_button_2")
        self.input_label_2 = QtWidgets.QLabel(self.str_tab)
        self.input_label_2.setGeometry(QtCore.QRect(20, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.input_label_2.setFont(font)
        self.input_label_2.setTextFormat(QtCore.Qt.AutoText)
        self.input_label_2.setWordWrap(False)
        self.input_label_2.setObjectName("input_label_2")
        self.plain_text_edit_2 = QtWidgets.QPlainTextEdit(self.str_tab)
        self.plain_text_edit_2.setGeometry(QtCore.QRect(19, 90, 231, 381))
        self.plain_text_edit_2.setFrameShape(QtWidgets.QFrame.Box)
        self.plain_text_edit_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plain_text_edit_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plain_text_edit_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.plain_text_edit_2.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.plain_text_edit_2.setObjectName("plain_text_edit_2")
        self.ciphertext_label_2 = QtWidgets.QLabel(self.str_tab)
        self.ciphertext_label_2.setGeometry(QtCore.QRect(339, 50, 51, 31))
        self.ciphertext_label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ciphertext_label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ciphertext_label_2.setObjectName("ciphertext_label_2")
        self.arrow_left_2 = QtWidgets.QLabel(self.str_tab)
        self.arrow_left_2.setGeometry(QtCore.QRect(250, 300, 81, 20))
        self.arrow_left_2.setObjectName("arrow_left_2")
        self.export_ciphertext_button_2 = QtWidgets.QPushButton(self.str_tab)
        self.export_ciphertext_button_2.setGeometry(QtCore.QRect(509, 50, 61, 31))
        self.export_ciphertext_button_2.setObjectName("export_ciphertext_button_2")
        self.encrypt_button_2 = QtWidgets.QPushButton(self.str_tab)
        self.encrypt_button_2.setGeometry(QtCore.QRect(261, 200, 61, 31))
        self.encrypt_button_2.setObjectName("encrypt_button_2")
        self.arrow_right_2 = QtWidgets.QLabel(self.str_tab)
        self.arrow_right_2.setGeometry(QtCore.QRect(250, 250, 81, 20))
        self.arrow_right_2.setObjectName("arrow_right_2")
        self.current_cipher_label = QtWidgets.QLabel(self.str_tab)
        self.current_cipher_label.setGeometry(QtCore.QRect(251, 269, 81, 31))
        self.current_cipher_label.setAlignment(QtCore.Qt.AlignCenter)
        self.current_cipher_label.setWordWrap(True)
        self.current_cipher_label.setIndent(-1)
        self.current_cipher_label.setOpenExternalLinks(False)
        self.current_cipher_label.setObjectName("current_cipher_label")
        self.switch_mode_with_key_tabwidget.addTab(self.str_tab, "")
        self.file_tab = QtWidgets.QWidget()
        self.file_tab.setObjectName("file_tab")
        self.check_key_3 = QtWidgets.QCheckBox(self.file_tab)
        self.check_key_3.setGeometry(QtCore.QRect(410, 16, 91, 20))
        self.check_key_3.setObjectName("check_key_3")
        self.ie_key_tool_button_3 = QtWidgets.QToolButton(self.file_tab)
        self.ie_key_tool_button_3.setGeometry(QtCore.QRect(510, 10, 61, 31))
        self.ie_key_tool_button_3.setObjectName("ie_key_tool_button_3")
        self.input_label_3 = QtWidgets.QLabel(self.file_tab)
        self.input_label_3.setGeometry(QtCore.QRect(20, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.input_label_3.setFont(font)
        self.input_label_3.setTextFormat(QtCore.Qt.AutoText)
        self.input_label_3.setWordWrap(False)
        self.input_label_3.setObjectName("input_label_3")
        self.input_key_3 = QtWidgets.QLineEdit(self.file_tab)
        self.input_key_3.setGeometry(QtCore.QRect(110, 10, 391, 31))
        self.input_key_3.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.input_key_3.setClearButtonEnabled(False)
        self.input_key_3.setObjectName("input_key_3")
        self.progress_bar_3 = QtWidgets.QProgressBar(self.file_tab)
        self.progress_bar_3.setGeometry(QtCore.QRect(20, 480, 551, 23))
        self.progress_bar_3.setProperty("value", 24)
        self.progress_bar_3.setObjectName("progress_bar_3")
        self.what_algorithm = QtWidgets.QLabel(self.file_tab)
        self.what_algorithm.setGeometry(QtCore.QRect(250, 240, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.what_algorithm.setFont(font)
        self.what_algorithm.setAlignment(QtCore.Qt.AlignCenter)
        self.what_algorithm.setObjectName("what_algorithm")
        self.layoutWidget = QtWidgets.QWidget(self.file_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(22, 275, 551, 201))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.decrypt_button_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.decrypt_button_3.setObjectName("decrypt_button_3")
        self.gridLayout_2.addWidget(self.decrypt_button_3, 0, 1, 1, 1)
        self.input_filename_label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.input_filename_label_2.setObjectName("input_filename_label_2")
        self.gridLayout_2.addWidget(self.input_filename_label_2, 1, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 1, 1, 1, 1)
        self.toolButton_3 = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_3.setObjectName("toolButton_3")
        self.gridLayout_2.addWidget(self.toolButton_3, 1, 2, 1, 1)
        self.save_to_label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.save_to_label_2.setObjectName("save_to_label_2")
        self.gridLayout_2.addWidget(self.save_to_label_2, 2, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 2, 1, 1, 1)
        self.path_button_2 = QtWidgets.QToolButton(self.layoutWidget)
        self.path_button_2.setObjectName("path_button_2")
        self.gridLayout_2.addWidget(self.path_button_2, 2, 2, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.file_tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(22, 52, 551, 201))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.encrypt_button_3 = QtWidgets.QPushButton(self.layoutWidget1)
        self.encrypt_button_3.setObjectName("encrypt_button_3")
        self.gridLayout.addWidget(self.encrypt_button_3, 0, 1, 1, 1)
        self.input_filename_label = QtWidgets.QLabel(self.layoutWidget1)
        self.input_filename_label.setObjectName("input_filename_label")
        self.gridLayout.addWidget(self.input_filename_label, 1, 0, 1, 1)
        self.import_file_path_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.import_file_path_edit.setObjectName("import_file_path_edit")
        self.gridLayout.addWidget(self.import_file_path_edit, 1, 1, 1, 1)
        self.import_file_button = QtWidgets.QToolButton(self.layoutWidget1)
        self.import_file_button.setObjectName("import_file_button")
        self.gridLayout.addWidget(self.import_file_button, 1, 2, 1, 1)
        self.save_to_label = QtWidgets.QLabel(self.layoutWidget1)
        self.save_to_label.setObjectName("save_to_label")
        self.gridLayout.addWidget(self.save_to_label, 2, 0, 1, 1)
        self.save_path_label = QtWidgets.QLineEdit(self.layoutWidget1)
        self.save_path_label.setObjectName("save_path_label")
        self.gridLayout.addWidget(self.save_path_label, 2, 1, 1, 1)
        self.path_button = QtWidgets.QToolButton(self.layoutWidget1)
        self.path_button.setObjectName("path_button")
        self.gridLayout.addWidget(self.path_button, 2, 2, 1, 1)
        self.layoutWidget.raise_()
        self.ie_key_tool_button_3.raise_()
        self.input_label_3.raise_()
        self.input_key_3.raise_()
        self.check_key_3.raise_()
        self.progress_bar_3.raise_()
        self.layoutWidget.raise_()
        self.what_algorithm.raise_()
        self.switch_mode_with_key_tabwidget.addTab(self.file_tab, "")
        self.switch_mode_without_key_tabwidget = QtWidgets.QTabWidget(self.single)
        self.switch_mode_without_key_tabwidget.setEnabled(True)
        self.switch_mode_without_key_tabwidget.setGeometry(QtCore.QRect(170, 9, 591, 541))
        self.switch_mode_without_key_tabwidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.switch_mode_without_key_tabwidget.setAcceptDrops(False)
        self.switch_mode_without_key_tabwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.switch_mode_without_key_tabwidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.switch_mode_without_key_tabwidget.setObjectName("switch_mode_without_key_tabwidget")
        self.str_tab_3 = QtWidgets.QWidget()
        self.str_tab_3.setObjectName("str_tab_3")
        self.plaintext_label_4 = QtWidgets.QLabel(self.str_tab_3)
        self.plaintext_label_4.setGeometry(QtCore.QRect(29, 50, 51, 31))
        self.plaintext_label_4.setObjectName("plaintext_label_4")
        self.import_plaintext_button_4 = QtWidgets.QPushButton(self.str_tab_3)
        self.import_plaintext_button_4.setGeometry(QtCore.QRect(189, 50, 61, 31))
        self.import_plaintext_button_4.setObjectName("import_plaintext_button_4")
        self.cipher_text_edit_4 = QtWidgets.QPlainTextEdit(self.str_tab_3)
        self.cipher_text_edit_4.setGeometry(QtCore.QRect(329, 90, 241, 381))
        self.cipher_text_edit_4.setFrameShape(QtWidgets.QFrame.Box)
        self.cipher_text_edit_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cipher_text_edit_4.setObjectName("cipher_text_edit_4")
        self.progress_bar_6 = QtWidgets.QProgressBar(self.str_tab_3)
        self.progress_bar_6.setGeometry(QtCore.QRect(20, 480, 551, 23))
        self.progress_bar_6.setProperty("value", 24)
        self.progress_bar_6.setObjectName("progress_bar_6")
        self.decrypt_button_6 = QtWidgets.QPushButton(self.str_tab_3)
        self.decrypt_button_6.setGeometry(QtCore.QRect(259, 340, 61, 31))
        self.decrypt_button_6.setObjectName("decrypt_button_6")
        self.plain_text_edit_4 = QtWidgets.QPlainTextEdit(self.str_tab_3)
        self.plain_text_edit_4.setGeometry(QtCore.QRect(19, 90, 231, 381))
        self.plain_text_edit_4.setFrameShape(QtWidgets.QFrame.Box)
        self.plain_text_edit_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plain_text_edit_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plain_text_edit_4.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.plain_text_edit_4.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.plain_text_edit_4.setObjectName("plain_text_edit_4")
        self.ciphertext_label_4 = QtWidgets.QLabel(self.str_tab_3)
        self.ciphertext_label_4.setGeometry(QtCore.QRect(339, 50, 51, 31))
        self.ciphertext_label_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ciphertext_label_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ciphertext_label_4.setObjectName("ciphertext_label_4")
        self.arrow_left_4 = QtWidgets.QLabel(self.str_tab_3)
        self.arrow_left_4.setGeometry(QtCore.QRect(250, 300, 81, 20))
        self.arrow_left_4.setObjectName("arrow_left_4")
        self.export_ciphertext_button_4 = QtWidgets.QPushButton(self.str_tab_3)
        self.export_ciphertext_button_4.setGeometry(QtCore.QRect(509, 50, 61, 31))
        self.export_ciphertext_button_4.setObjectName("export_ciphertext_button_4")
        self.encrypt_button_6 = QtWidgets.QPushButton(self.str_tab_3)
        self.encrypt_button_6.setGeometry(QtCore.QRect(261, 200, 61, 31))
        self.encrypt_button_6.setObjectName("encrypt_button_6")
        self.arrow_right_4 = QtWidgets.QLabel(self.str_tab_3)
        self.arrow_right_4.setGeometry(QtCore.QRect(250, 250, 81, 20))
        self.arrow_right_4.setObjectName("arrow_right_4")
        self.current_cipher_label_3 = QtWidgets.QLabel(self.str_tab_3)
        self.current_cipher_label_3.setGeometry(QtCore.QRect(251, 269, 81, 31))
        self.current_cipher_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.current_cipher_label_3.setWordWrap(True)
        self.current_cipher_label_3.setIndent(-1)
        self.current_cipher_label_3.setOpenExternalLinks(False)
        self.current_cipher_label_3.setObjectName("current_cipher_label_3")
        self.generate_keypair_button = QtWidgets.QPushButton(self.str_tab_3)
        self.generate_keypair_button.setGeometry(QtCore.QRect(20, 10, 93, 31))
        self.generate_keypair_button.setObjectName("generate_keypair_button")
        self.show_keypair_text = QtWidgets.QTextBrowser(self.str_tab_3)
        self.show_keypair_text.setGeometry(QtCore.QRect(120, 10, 381, 31))
        self.show_keypair_text.setObjectName("show_keypair_text")
        self.export_keypair_toolButton = QtWidgets.QToolButton(self.str_tab_3)
        self.export_keypair_toolButton.setGeometry(QtCore.QRect(510, 10, 61, 31))
        self.export_keypair_toolButton.setObjectName("export_keypair_toolButton")
        self.switch_mode_without_key_tabwidget.addTab(self.str_tab_3, "")
        self.file_tab_3 = QtWidgets.QWidget()
        self.file_tab_3.setObjectName("file_tab_3")
        self.progress_bar_7 = QtWidgets.QProgressBar(self.file_tab_3)
        self.progress_bar_7.setGeometry(QtCore.QRect(20, 480, 551, 23))
        self.progress_bar_7.setProperty("value", 24)
        self.progress_bar_7.setObjectName("progress_bar_7")
        self.layoutWidget_2 = QtWidgets.QWidget(self.file_tab_3)
        self.layoutWidget_2.setGeometry(QtCore.QRect(21, 51, 551, 421))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.encrypt_button_7 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.encrypt_button_7.setObjectName("encrypt_button_7")
        self.gridLayout_5.addWidget(self.encrypt_button_7, 0, 1, 1, 1)
        self.input_filename_label_5 = QtWidgets.QLabel(self.layoutWidget_2)
        self.input_filename_label_5.setObjectName("input_filename_label_5")
        self.gridLayout_5.addWidget(self.input_filename_label_5, 1, 0, 1, 1)
        self.import_file_path_edit_3 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.import_file_path_edit_3.setObjectName("import_file_path_edit_3")
        self.gridLayout_5.addWidget(self.import_file_path_edit_3, 1, 1, 1, 1)
        self.import_file_button_3 = QtWidgets.QToolButton(self.layoutWidget_2)
        self.import_file_button_3.setObjectName("import_file_button_3")
        self.gridLayout_5.addWidget(self.import_file_button_3, 1, 2, 1, 1)
        self.save_to_label_5 = QtWidgets.QLabel(self.layoutWidget_2)
        self.save_to_label_5.setObjectName("save_to_label_5")
        self.gridLayout_5.addWidget(self.save_to_label_5, 2, 0, 1, 1)
        self.save_path_label_3 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.save_path_label_3.setObjectName("save_path_label_3")
        self.gridLayout_5.addWidget(self.save_path_label_3, 2, 1, 1, 1)
        self.path_button_5 = QtWidgets.QToolButton(self.layoutWidget_2)
        self.path_button_5.setObjectName("path_button_5")
        self.gridLayout_5.addWidget(self.path_button_5, 2, 2, 1, 1)
        self.verticalLayout_12.addLayout(self.gridLayout_5)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.decrypt_button_7 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.decrypt_button_7.setObjectName("decrypt_button_7")
        self.gridLayout_6.addWidget(self.decrypt_button_7, 0, 1, 1, 1)
        self.input_filename_label_6 = QtWidgets.QLabel(self.layoutWidget_2)
        self.input_filename_label_6.setObjectName("input_filename_label_6")
        self.gridLayout_6.addWidget(self.input_filename_label_6, 1, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_6.addWidget(self.lineEdit_7, 1, 1, 1, 1)
        self.toolButton_5 = QtWidgets.QToolButton(self.layoutWidget_2)
        self.toolButton_5.setObjectName("toolButton_5")
        self.gridLayout_6.addWidget(self.toolButton_5, 1, 2, 1, 1)
        self.save_to_label_6 = QtWidgets.QLabel(self.layoutWidget_2)
        self.save_to_label_6.setObjectName("save_to_label_6")
        self.gridLayout_6.addWidget(self.save_to_label_6, 2, 0, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_6.addWidget(self.lineEdit_8, 2, 1, 1, 1)
        self.path_button_6 = QtWidgets.QToolButton(self.layoutWidget_2)
        self.path_button_6.setObjectName("path_button_6")
        self.gridLayout_6.addWidget(self.path_button_6, 2, 2, 1, 1)
        self.verticalLayout_12.addLayout(self.gridLayout_6)
        self.what_algorithm_2 = QtWidgets.QLabel(self.file_tab_3)
        self.what_algorithm_2.setGeometry(QtCore.QRect(250, 240, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.what_algorithm_2.setFont(font)
        self.what_algorithm_2.setAlignment(QtCore.Qt.AlignCenter)
        self.what_algorithm_2.setObjectName("what_algorithm_2")
        self.generate_keypair_button_2 = QtWidgets.QPushButton(self.file_tab_3)
        self.generate_keypair_button_2.setGeometry(QtCore.QRect(20, 10, 93, 31))
        self.generate_keypair_button_2.setObjectName("generate_keypair_button_2")
        self.show_keypair_text_2 = QtWidgets.QTextBrowser(self.file_tab_3)
        self.show_keypair_text_2.setGeometry(QtCore.QRect(120, 10, 381, 31))
        self.show_keypair_text_2.setObjectName("show_keypair_text_2")
        self.export_keypair_toolButton_2 = QtWidgets.QToolButton(self.file_tab_3)
        self.export_keypair_toolButton_2.setGeometry(QtCore.QRect(510, 10, 61, 31))
        self.export_keypair_toolButton_2.setObjectName("export_keypair_toolButton_2")
        self.switch_mode_without_key_tabwidget.addTab(self.file_tab_3, "")
        self.md5_frame = QtWidgets.QFrame(self.single)
        self.md5_frame.setGeometry(QtCore.QRect(170, 10, 591, 541))
        self.md5_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.md5_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.md5_frame.setObjectName("md5_frame")
        self.md5_show_text = QtWidgets.QTextBrowser(self.md5_frame)
        self.md5_show_text.setGeometry(QtCore.QRect(20, 440, 551, 31))
        self.md5_show_text.setObjectName("md5_show_text")
        self.lineEdit = QtWidgets.QLineEdit(self.md5_frame)
        self.lineEdit.setGeometry(QtCore.QRect(100, 20, 391, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.daoruwenjian_label = QtWidgets.QLabel(self.md5_frame)
        self.daoruwenjian_label.setGeometry(QtCore.QRect(20, 20, 81, 31))
        self.daoruwenjian_label.setObjectName("daoruwenjian_label")
        self.import_file_toolbox = QtWidgets.QToolButton(self.md5_frame)
        self.import_file_toolbox.setGeometry(QtCore.QRect(500, 20, 71, 31))
        self.import_file_toolbox.setObjectName("import_file_toolbox")
        self.progressBar = QtWidgets.QProgressBar(self.md5_frame)
        self.progressBar.setGeometry(QtCore.QRect(20, 490, 551, 31))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.md5_label = QtWidgets.QLabel(self.md5_frame)
        self.md5_label.setGeometry(QtCore.QRect(20, 400, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.md5_label.setFont(font)
        self.md5_label.setObjectName("md5_label")
        self.shuruzifuchuan_label = QtWidgets.QLabel(self.md5_frame)
        self.shuruzifuchuan_label.setGeometry(QtCore.QRect(20, 60, 91, 31))
        self.shuruzifuchuan_label.setObjectName("shuruzifuchuan_label")
        self.layoutWidget2 = QtWidgets.QWidget(self.md5_frame)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 100, 551, 291))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.input_edit = QtWidgets.QPlainTextEdit(self.layoutWidget2)
        self.input_edit.setObjectName("input_edit")
        self.verticalLayout_13.addWidget(self.input_edit)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_13.addWidget(self.pushButton)
        self.base_frame = QtWidgets.QFrame(self.single)
        self.base_frame.setGeometry(QtCore.QRect(169, 9, 591, 541))
        self.base_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.base_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.base_frame.setObjectName("base_frame")
        self.base_frame.raise_()
        self.cipher_switch_toolbox.raise_()
        self.cipher_with_key_frame.raise_()
        self.md5_frame.raise_()
        self.switch_mode_without_key_tabwidget.raise_()
        self.switch_mode_with_key_tabwidget.raise_()
        self.switch_sd.addWidget(self.single)
        self.dual = QtWidgets.QWidget()
        self.dual.setObjectName("dual")
        self.switch_sd.addWidget(self.dual)
        main_window.setCentralWidget(self.centralwidget)

        # 初始化状态栏
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)

        # 面板初始可见性设置
        self.base_frame.setVisible(True)
        self.cipher_with_key_frame.setVisible(False)
        self.switch_mode_with_key_tabwidget.setVisible(False)
        self.switch_mode_without_key_tabwidget.setVisible(False)
        self.md5_frame.setVisible(False)

        # 初始化正则表达式：仅能输入大小写字母和数字
        self.regx = QRegExp("[a-zA-Z0-9]+$")
        self.regx_2 = QRegExp("[0-9]+$")
        self.regx_3 = QRegExp("[a-zA-Z]+$")
        self.regx_4 = QRegExp("[0-9 ]+$")
        self.regx_5 = QRegExp("[a-zA-Z ]+$")

        # 古典密码部件设置
        self.input_key.setEchoMode(QLineEdit.Password)
        self.classical_validator_1 = QRegExpValidator(self.regx, self.input_key)
        self.classical_validator_2 = QRegExpValidator(self.regx_2, self.input_key)
        self.classical_validator_3 = QRegExpValidator(self.regx_3, self.input_key)
        self.classical_validator_4 = QRegExpValidator(self.regx_4, self.input_key)
        self.classical_validator_5 = QRegExpValidator(self.regx_5, self.input_key)


        # QToolbox下拉菜单
        self.ie_key_tool_button.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.ie_menu = QMenu()
        self.ie_menu.addAction("导入", self.import_1)
        self.ie_menu.addAction("导出", self.import_1)
        self.ie_key_tool_button.setMenu(self.ie_menu)

        # 流密码+分组密码部件设置
        self.input_key_2.setEchoMode(QLineEdit.Password)
        self.input_key_3.setEchoMode(QLineEdit.Password)
        self.block_validator_1 = QRegExpValidator(self.regx, self.input_key_2)
        self.block_validator_2 = QRegExpValidator(self.regx, self.input_key_3)
        self.block_validator_3 = QRegExpValidator(self.regx_2, self.input_key_2)
        self.block_validator_4 = QRegExpValidator(self.regx_2, self.input_key_3)
        # 公钥密码部件设置


        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "单机加解密"))
        self.kaisa.setText(_translate("MainWindow", "凯撒密码"))
        self.guanjianzi.setText(_translate("MainWindow", "关键字密码"))
        self.fangshe.setText(_translate("MainWindow", "仿射密码"))
        self.duobian.setText(_translate("MainWindow", "多边密码"))
        self.classical_cipher_switch.setItemText(self.classical_cipher_switch.indexOf(self.danbiaotidai), _translate("MainWindow", "单表替代密码"))
        self.weijiniya.setText(_translate("MainWindow", "维吉尼亚密码"))
        self.autokeymi.setText(_translate("MainWindow", "Autokey密文"))
        self.autokeyming.setText(_translate("MainWindow", "Autokey明文"))
        self.classical_cipher_switch.setItemText(self.classical_cipher_switch.indexOf(self.duobiaotidai), _translate("MainWindow", "多表替代密码"))
        self.boleifei.setText(_translate("MainWindow", "波雷费密码"))
        self.classical_cipher_switch.setItemText(self.classical_cipher_switch.indexOf(self.duotutidai), _translate("MainWindow", "多图替代密码"))
        self.zhihuan.setText(_translate("MainWindow", "置换密码"))
        self.liezhihuan.setText(_translate("MainWindow", "列置换密码"))
        self.shuangchongzhihuan.setText(_translate("MainWindow", "双重置换密码"))
        self.classical_cipher_switch.setItemText(self.classical_cipher_switch.indexOf(self.zhihuan_2), _translate("MainWindow", "置换密码"))
        self.cipher_switch_toolbox.setItemText(self.cipher_switch_toolbox.indexOf(self.gudianmima), _translate("MainWindow", "古典密码"))
        self.RC4.setText(_translate("MainWindow", "RC4"))
        self.CA.setText(_translate("MainWindow", "CA"))
        self.cipher_switch_toolbox.setItemText(self.cipher_switch_toolbox.indexOf(self.liumima), _translate("MainWindow", "流密码"))
        self.DES.setText(_translate("MainWindow", "DES"))
        self.AES.setText(_translate("MainWindow", "AES"))
        self.cipher_switch_toolbox.setItemText(self.cipher_switch_toolbox.indexOf(self.fenzumima), _translate("MainWindow", "分组密码"))
        self.RSA.setText(_translate("MainWindow", "RSA"))
        self.ECC.setText(_translate("MainWindow", "ECC"))
        self.cipher_switch_toolbox.setItemText(self.cipher_switch_toolbox.indexOf(self.gongyaomima), _translate("MainWindow", "公钥密码"))
        self.MD5.setText(_translate("MainWindow", "MD5"))
        self.cipher_switch_toolbox.setItemText(self.cipher_switch_toolbox.indexOf(self.danxiangsanlie), _translate("MainWindow", "单向散列函数"))
        self.cipher_switch_toolbox.setItemText(self.cipher_switch_toolbox.indexOf(self.guanyu), _translate("MainWindow", "关于"))
        self.input_label.setText(_translate("MainWindow", "请输入密钥："))
        self.ie_key_tool_button.setText(_translate("MainWindow", "..."))
        self.plaintext_label.setText(_translate("MainWindow", "明文："))
        self.import_plaintext_button.setText(_translate("MainWindow", "导入"))
        self.export_ciphertext_button.setText(_translate("MainWindow", "导出"))
        self.ciphertext_label.setText(_translate("MainWindow", "密文："))
        self.encrypt_button.setText(_translate("MainWindow", "加密"))
        self.decrypt_button.setText(_translate("MainWindow", "解密"))
        self.arrow_right.setText(_translate("MainWindow", "-------->>"))
        self.arrow_left.setText(_translate("MainWindow", "<<--------"))
        self.check_key.setText(_translate("MainWindow", "显示密钥"))
        self.label.setText(_translate("MainWindow", "凯撒密码"))
        self.ie_key_tool_button_2.setText(_translate("MainWindow", "..."))
        self.plaintext_label_2.setText(_translate("MainWindow", "明文："))
        self.import_plaintext_button_2.setText(_translate("MainWindow", "导入"))
        self.check_key_2.setText(_translate("MainWindow", "显示密钥"))
        self.decrypt_button_2.setText(_translate("MainWindow", "解密"))
        self.input_label_2.setText(_translate("MainWindow", "请输入密钥："))
        self.ciphertext_label_2.setText(_translate("MainWindow", "密文："))
        self.arrow_left_2.setText(_translate("MainWindow", "<<--------"))
        self.export_ciphertext_button_2.setText(_translate("MainWindow", "导出"))
        self.encrypt_button_2.setText(_translate("MainWindow", "加密"))
        self.arrow_right_2.setText(_translate("MainWindow", "-------->>"))
        self.current_cipher_label.setText(_translate("MainWindow", "DES"))
        self.switch_mode_with_key_tabwidget.setTabText(self.switch_mode_with_key_tabwidget.indexOf(self.str_tab), _translate("MainWindow", "字符串加解密"))
        self.check_key_3.setText(_translate("MainWindow", "显示密钥"))
        self.ie_key_tool_button_3.setText(_translate("MainWindow", "..."))
        self.input_label_3.setText(_translate("MainWindow", "请输入密钥："))
        self.what_algorithm.setText(_translate("MainWindow", "RC4"))
        self.decrypt_button_3.setText(_translate("MainWindow", "解密"))
        self.input_filename_label_2.setText(_translate("MainWindow", "导入文件："))
        self.toolButton_3.setText(_translate("MainWindow", "..."))
        self.save_to_label_2.setText(_translate("MainWindow", "保存至："))
        self.path_button_2.setText(_translate("MainWindow", "..."))
        self.encrypt_button_3.setText(_translate("MainWindow", "加密"))
        self.input_filename_label.setText(_translate("MainWindow", "导入文件："))
        self.import_file_button.setText(_translate("MainWindow", "..."))
        self.save_to_label.setText(_translate("MainWindow", "保存至："))
        self.path_button.setText(_translate("MainWindow", "..."))
        self.switch_mode_with_key_tabwidget.setTabText(self.switch_mode_with_key_tabwidget.indexOf(self.file_tab), _translate("MainWindow", "文件加解密"))
        self.plaintext_label_4.setText(_translate("MainWindow", "明文："))
        self.import_plaintext_button_4.setText(_translate("MainWindow", "导入"))
        self.decrypt_button_6.setText(_translate("MainWindow", "解密"))
        self.ciphertext_label_4.setText(_translate("MainWindow", "密文："))
        self.arrow_left_4.setText(_translate("MainWindow", "<<--------"))
        self.export_ciphertext_button_4.setText(_translate("MainWindow", "导出"))
        self.encrypt_button_6.setText(_translate("MainWindow", "加密"))
        self.arrow_right_4.setText(_translate("MainWindow", "-------->>"))
        self.current_cipher_label_3.setText(_translate("MainWindow", "RSA"))
        self.generate_keypair_button.setText(_translate("MainWindow", "生成密钥对"))
        self.export_keypair_toolButton.setText(_translate("MainWindow", "..."))
        self.switch_mode_without_key_tabwidget.setTabText(self.switch_mode_without_key_tabwidget.indexOf(self.str_tab_3), _translate("MainWindow", "字符串加解密"))
        self.encrypt_button_7.setText(_translate("MainWindow", "加密"))
        self.input_filename_label_5.setText(_translate("MainWindow", "导入文件："))
        self.import_file_button_3.setText(_translate("MainWindow", "..."))
        self.save_to_label_5.setText(_translate("MainWindow", "保存至："))
        self.path_button_5.setText(_translate("MainWindow", "..."))
        self.decrypt_button_7.setText(_translate("MainWindow", "解密"))
        self.input_filename_label_6.setText(_translate("MainWindow", "导入文件："))
        self.toolButton_5.setText(_translate("MainWindow", "..."))
        self.save_to_label_6.setText(_translate("MainWindow", "保存至："))
        self.path_button_6.setText(_translate("MainWindow", "..."))
        self.what_algorithm_2.setText(_translate("MainWindow", "RC4"))
        self.generate_keypair_button_2.setText(_translate("MainWindow", "生成密钥对"))
        self.export_keypair_toolButton_2.setText(_translate("MainWindow", "..."))
        self.switch_mode_without_key_tabwidget.setTabText(self.switch_mode_without_key_tabwidget.indexOf(self.file_tab_3), _translate("MainWindow", "文件加解密"))
        self.daoruwenjian_label.setText(_translate("MainWindow", "导入文件："))
        self.import_file_toolbox.setText(_translate("MainWindow", "..."))
        self.md5_label.setText(_translate("MainWindow", "MD5："))
        self.shuruzifuchuan_label.setText(_translate("MainWindow", "输入字符串："))
        self.pushButton.setText(_translate("MainWindow", "生成MD5"))

    def import_1(self):
        pass
