"""
主窗口 UI 定义：
说明：
- 保持原有功能与部件命名对外接口不变，避免影响事件绑定逻辑
- 将初始化中的校验器与菜单配置拆分为独立方法，便于维护与阅读
- 移除明显的汉语拼音变量命名，统一改为更语义化的英文命名
"""

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QRegExp
from PyQt5.QtGui import QRegExpValidator
from PyQt5.QtWidgets import QLineEdit, QMenu

from assets.python import qss_reader


class UiMainWindow(QtWidgets.QMainWindow):

    def __init__(self, main_window):
        super().__init__()
        # self.qss_style = qss_reader.QssReader.read_qss('./assets/qss/darkstyle.qss')
        # main_window.setStyleSheet(self.qss_style)
        self.setup_ui(main_window)

    def setup_ui(self, main_window):
        main_window.setObjectName("MainWindow")
        main_window.resize(812, 600)
        main_window.setFixedSize(main_window.width(), main_window.height())
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./assets/icons/PentestBox.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        main_window.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.switch_sd = QtWidgets.QStackedWidget(self.centralwidget)
        self.switch_sd.setGeometry(QtCore.QRect(10, 10, 791, 551))
        self.switch_sd.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.switch_sd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.switch_sd.setObjectName("switch_sd")
        self.single = QtWidgets.QWidget()
        self.single.setObjectName("single")
        self.cipher_switch_toolbox = QtWidgets.QToolBox(self.single)
        self.cipher_switch_toolbox.setGeometry(QtCore.QRect(10, 10, 151, 541))
        self.cipher_switch_toolbox.setFrameShape(QtWidgets.QFrame.Panel)
        self.cipher_switch_toolbox.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cipher_switch_toolbox.setObjectName("cipher_switch_toolbox")
        self.classical_cipher_page = QtWidgets.QWidget()
        self.classical_cipher_page.setGeometry(QtCore.QRect(0, 0, 149, 359))
        self.classical_cipher_page.setObjectName("classical_cipher_page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.classical_cipher_page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.classical_cipher_switch = QtWidgets.QToolBox(self.classical_cipher_page)
        self.classical_cipher_switch.setFrameShape(QtWidgets.QFrame.Panel)
        self.classical_cipher_switch.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.classical_cipher_switch.setObjectName("classical_cipher_switch")
        self.single_substitution_page = QtWidgets.QWidget()
        self.single_substitution_page.setGeometry(QtCore.QRect(0, 0, 125, 215))
        self.single_substitution_page.setObjectName("single_substitution_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.single_substitution_page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.caesar = QtWidgets.QPushButton(self.single_substitution_page)
        self.caesar.setCheckable(True)
        self.caesar.setChecked(False)
        self.caesar.setDefault(True)
        self.caesar.setFlat(True)
        self.caesar.setObjectName("caesar")
        self.button_group = QtWidgets.QButtonGroup(main_window)
        self.button_group.setObjectName("button_group")
        self.button_group.addButton(self.caesar)
        self.verticalLayout_4.addWidget(self.caesar)
        self.keyword = QtWidgets.QPushButton(self.single_substitution_page)
        self.keyword.setCheckable(True)
        self.keyword.setFlat(True)
        self.keyword.setObjectName("keyword")
        self.button_group.addButton(self.keyword)
        self.verticalLayout_4.addWidget(self.keyword)
        self.affine = QtWidgets.QPushButton(self.single_substitution_page)
        self.affine.setCheckable(True)
        self.affine.setFlat(True)
        self.affine.setObjectName("affine")
        self.button_group.addButton(self.affine)
        self.verticalLayout_4.addWidget(self.affine)
        self.multilateral = QtWidgets.QPushButton(self.single_substitution_page)
        self.multilateral.setCheckable(True)
        self.multilateral.setFlat(True)
        self.multilateral.setObjectName("multilateral")
        self.button_group.addButton(self.multilateral)
        self.verticalLayout_4.addWidget(self.multilateral)
        self.classical_cipher_switch.addItem(self.single_substitution_page, "")
        self.multiple_substitution_page = QtWidgets.QWidget()
        self.multiple_substitution_page.setGeometry(QtCore.QRect(0, 0, 125, 215))
        self.multiple_substitution_page.setObjectName("multiple_substitution_page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.multiple_substitution_page)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.vigenere = QtWidgets.QPushButton(self.multiple_substitution_page)
        self.vigenere.setCheckable(True)
        self.vigenere.setDefault(True)
        self.vigenere.setFlat(True)
        self.vigenere.setObjectName("vigenere")
        self.button_group.addButton(self.vigenere)
        self.verticalLayout_5.addWidget(self.vigenere)
        self.autokey_ciphertext = QtWidgets.QPushButton(self.multiple_substitution_page)
        self.autokey_ciphertext.setCheckable(True)
        self.autokey_ciphertext.setFlat(True)
        self.autokey_ciphertext.setObjectName("autokey_ciphertext")
        self.button_group.addButton(self.autokey_ciphertext)
        self.verticalLayout_5.addWidget(self.autokey_ciphertext)
        self.autokey_plaintext = QtWidgets.QPushButton(self.multiple_substitution_page)
        self.autokey_plaintext.setCheckable(True)
        self.autokey_plaintext.setFlat(True)
        self.autokey_plaintext.setObjectName("autokey_plaintext")
        self.button_group.addButton(self.autokey_plaintext)
        self.verticalLayout_5.addWidget(self.autokey_plaintext)
        self.classical_cipher_switch.addItem(self.multiple_substitution_page, "")
        self.polygraph_substitution_page = QtWidgets.QWidget()
        self.polygraph_substitution_page.setGeometry(QtCore.QRect(0, 0, 125, 215))
        self.polygraph_substitution_page.setObjectName("polygraph_substitution_page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.polygraph_substitution_page)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.playfair = QtWidgets.QPushButton(self.polygraph_substitution_page)
        self.playfair.setCheckable(True)
        self.playfair.setDefault(True)
        self.playfair.setFlat(True)
        self.playfair.setObjectName("playfair")
        self.button_group.addButton(self.playfair)
        self.verticalLayout_6.addWidget(self.playfair)
        self.classical_cipher_switch.addItem(self.polygraph_substitution_page, "")
        self.transposition_page = QtWidgets.QWidget()
        self.transposition_page.setGeometry(QtCore.QRect(0, 0, 125, 215))
        self.transposition_page.setObjectName("transposition_page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.transposition_page)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.permutation = QtWidgets.QPushButton(self.transposition_page)
        self.permutation.setCheckable(True)
        self.permutation.setDefault(True)
        self.permutation.setFlat(True)
        self.permutation.setObjectName("permutation")
        self.button_group.addButton(self.permutation)
        self.verticalLayout_7.addWidget(self.permutation)
        self.column_permutation = QtWidgets.QPushButton(self.transposition_page)
        self.column_permutation.setCheckable(True)
        self.column_permutation.setFlat(True)
        self.column_permutation.setObjectName("column_permutation")
        self.button_group.addButton(self.column_permutation)
        self.verticalLayout_7.addWidget(self.column_permutation)
        self.double_transposition = QtWidgets.QPushButton(self.transposition_page)
        self.double_transposition.setCheckable(True)
        self.double_transposition.setFlat(True)
        self.double_transposition.setObjectName("double_transposition")
        self.button_group.addButton(self.double_transposition)
        self.verticalLayout_7.addWidget(self.double_transposition)
        self.classical_cipher_switch.addItem(self.transposition_page, "")
        self.verticalLayout.addWidget(self.classical_cipher_switch)
        self.cipher_switch_toolbox.addItem(self.classical_cipher_page, "")
        self.stream_cipher_page = QtWidgets.QWidget()
        self.stream_cipher_page.setGeometry(QtCore.QRect(0, 0, 149, 359))
        self.stream_cipher_page.setObjectName("stream_cipher_page")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.stream_cipher_page)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.RC4 = QtWidgets.QPushButton(self.stream_cipher_page)
        self.RC4.setCheckable(True)
        self.RC4.setAutoDefault(False)
        self.RC4.setDefault(True)
        self.RC4.setFlat(True)
        self.RC4.setObjectName("RC4")
        self.button_group.addButton(self.RC4)
        self.verticalLayout_8.addWidget(self.RC4)
        self.CA = QtWidgets.QPushButton(self.stream_cipher_page)
        self.CA.setCheckable(True)
        self.CA.setDefault(False)
        self.CA.setFlat(True)
        self.CA.setObjectName("CA")
        self.button_group.addButton(self.CA)
        self.verticalLayout_8.addWidget(self.CA)
        self.cipher_switch_toolbox.addItem(self.stream_cipher_page, "")
        self.block_cipher_page = QtWidgets.QWidget()
        self.block_cipher_page.setGeometry(QtCore.QRect(0, 0, 149, 359))
        self.block_cipher_page.setObjectName("block_cipher_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.block_cipher_page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.DES = QtWidgets.QPushButton(self.block_cipher_page)
        self.DES.setCheckable(True)
        self.DES.setDefault(True)
        self.DES.setFlat(True)
        self.DES.setObjectName("DES")
        self.button_group.addButton(self.DES)
        self.verticalLayout_2.addWidget(self.DES)
        self.AES = QtWidgets.QPushButton(self.block_cipher_page)
        self.AES.setCheckable(True)
        self.AES.setFlat(True)
        self.AES.setObjectName("aes")
        self.button_group.addButton(self.AES)
        self.verticalLayout_2.addWidget(self.AES)
        self.cipher_switch_toolbox.addItem(self.block_cipher_page, "")
        self.public_key_page = QtWidgets.QWidget()
        self.public_key_page.setGeometry(QtCore.QRect(0, 0, 149, 359))
        self.public_key_page.setObjectName("public_key_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.public_key_page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.RSA = QtWidgets.QPushButton(self.public_key_page)
        self.RSA.setCheckable(True)
        self.RSA.setFlat(True)
        self.RSA.setObjectName("RSA")
        self.button_group.addButton(self.RSA)
        self.verticalLayout_3.addWidget(self.RSA)
        self.ECC = QtWidgets.QPushButton(self.public_key_page)
        self.ECC.setCheckable(True)
        self.ECC.setFlat(True)
        self.ECC.setObjectName("ECC")
        self.button_group.addButton(self.ECC)
        self.verticalLayout_3.addWidget(self.ECC)
        self.cipher_switch_toolbox.addItem(self.public_key_page, "")
        self.hash_page = QtWidgets.QWidget()
        self.hash_page.setGeometry(QtCore.QRect(0, 0, 149, 359))
        self.hash_page.setObjectName("hash_page")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.hash_page)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.MD5 = QtWidgets.QPushButton(self.hash_page)
        self.MD5.setCheckable(True)
        self.MD5.setFlat(True)
        self.MD5.setObjectName("MD5")
        self.button_group.addButton(self.MD5)
        self.verticalLayout_9.addWidget(self.MD5)
        self.cipher_switch_toolbox.addItem(self.hash_page, "")
        self.about_page = QtWidgets.QWidget()
        self.about_page.setGeometry(QtCore.QRect(0, 0, 149, 359))
        self.about_page.setObjectName("about_page")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.about_page)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.about = QtWidgets.QTextBrowser(self.about_page)
        self.about.setFrameShape(QtWidgets.QFrame.Panel)
        self.about.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.about.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.about.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.about.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.about.setOpenExternalLinks(False)
        self.about.setObjectName("about")
        self.horizontalLayout.addWidget(self.about)
        self.cipher_switch_toolbox.addItem(self.about_page, "")
        self.cipher_with_key_frame = QtWidgets.QFrame(self.single)
        self.cipher_with_key_frame.setGeometry(QtCore.QRect(170, 10, 591, 541))
        self.cipher_with_key_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.cipher_with_key_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cipher_with_key_frame.setObjectName("cipher_with_key_frame")
        self.input_label = QtWidgets.QLabel(self.cipher_with_key_frame)
        self.input_label.setGeometry(QtCore.QRect(20, 20, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.input_label.setFont(font)
        self.input_label.setTextFormat(QtCore.Qt.AutoText)
        self.input_label.setWordWrap(False)
        self.input_label.setObjectName("input_label")
        self.input_key = QtWidgets.QLineEdit(self.cipher_with_key_frame)
        self.input_key.setGeometry(QtCore.QRect(110, 20, 391, 31))
        self.input_key.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.input_key.setClearButtonEnabled(False)
        self.input_key.setObjectName("input_key")
        self.ie_key_tool_button = QtWidgets.QToolButton(self.cipher_with_key_frame)
        self.ie_key_tool_button.setGeometry(QtCore.QRect(510, 20, 61, 31))
        self.ie_key_tool_button.setObjectName("ie_key_tool_button")
        self.progress_bar = QtWidgets.QProgressBar(self.cipher_with_key_frame)
        self.progress_bar.setGeometry(QtCore.QRect(20, 500, 551, 23))
        self.progress_bar.setProperty("value", 24)
        self.progress_bar.setObjectName("progress_bar")
        self.cipher_text_edit = QtWidgets.QPlainTextEdit(self.cipher_with_key_frame)
        self.cipher_text_edit.setGeometry(QtCore.QRect(330, 100, 241, 381))
        self.cipher_text_edit.setFrameShape(QtWidgets.QFrame.Box)
        self.cipher_text_edit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cipher_text_edit.setObjectName("cipher_text_edit")
        self.plain_text_edit = QtWidgets.QPlainTextEdit(self.cipher_with_key_frame)
        self.plain_text_edit.setGeometry(QtCore.QRect(20, 100, 231, 381))
        self.plain_text_edit.setFrameShape(QtWidgets.QFrame.Box)
        self.plain_text_edit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plain_text_edit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plain_text_edit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.plain_text_edit.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.plain_text_edit.setObjectName("plain_text_edit")
        self.plaintext_label = QtWidgets.QLabel(self.cipher_with_key_frame)
        self.plaintext_label.setGeometry(QtCore.QRect(30, 60, 51, 31))
        self.plaintext_label.setObjectName("plaintext_label")
        self.import_plaintext_button = QtWidgets.QPushButton(self.cipher_with_key_frame)
        self.import_plaintext_button.setGeometry(QtCore.QRect(190, 60, 61, 31))
        self.import_plaintext_button.setObjectName("import_plaintext_button")
        self.export_ciphertext_button = QtWidgets.QPushButton(self.cipher_with_key_frame)
        self.export_ciphertext_button.setGeometry(QtCore.QRect(510, 60, 61, 31))
        self.export_ciphertext_button.setObjectName("export_ciphertext_button")
        self.ciphertext_label = QtWidgets.QLabel(self.cipher_with_key_frame)
        self.ciphertext_label.setGeometry(QtCore.QRect(340, 60, 51, 31))
        self.ciphertext_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ciphertext_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ciphertext_label.setObjectName("ciphertext_label")
        self.encrypt_button = QtWidgets.QPushButton(self.cipher_with_key_frame)
        self.encrypt_button.setGeometry(QtCore.QRect(262, 210, 61, 31))
        self.encrypt_button.setObjectName("encrypt_button")
        self.decrypt_button = QtWidgets.QPushButton(self.cipher_with_key_frame)
        self.decrypt_button.setGeometry(QtCore.QRect(260, 350, 61, 31))
        self.decrypt_button.setObjectName("decrypt_button")
        self.arrow_right = QtWidgets.QLabel(self.cipher_with_key_frame)
        self.arrow_right.setGeometry(QtCore.QRect(251, 260, 81, 20))
        self.arrow_right.setObjectName("arrow_right")
        self.arrow_left = QtWidgets.QLabel(self.cipher_with_key_frame)
        self.arrow_left.setGeometry(QtCore.QRect(251, 310, 81, 20))
        self.arrow_left.setObjectName("arrow_left")
        self.check_key = QtWidgets.QCheckBox(self.cipher_with_key_frame)
        self.check_key.setGeometry(QtCore.QRect(410, 26, 91, 20))
        self.check_key.setObjectName("check_key")
        self.label = QtWidgets.QLabel(self.cipher_with_key_frame)
        self.label.setGeometry(QtCore.QRect(250, 285, 81, 21))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.switch_mode_with_key_tabwidget = QtWidgets.QTabWidget(self.single)
        self.switch_mode_with_key_tabwidget.setEnabled(True)
        self.switch_mode_with_key_tabwidget.setGeometry(QtCore.QRect(170, 10, 591, 541))
        self.switch_mode_with_key_tabwidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.switch_mode_with_key_tabwidget.setAcceptDrops(False)
        self.switch_mode_with_key_tabwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.switch_mode_with_key_tabwidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.switch_mode_with_key_tabwidget.setObjectName("switch_mode_with_key_tabwidget")
        self.str_tab = QtWidgets.QWidget()
        self.str_tab.setObjectName("str_tab")
        self.string_ie_key_tool_button = QtWidgets.QToolButton(self.str_tab)
        self.string_ie_key_tool_button.setGeometry(QtCore.QRect(510, 10, 61, 31))
        self.string_ie_key_tool_button.setObjectName("ie_key_tool_button_2")
        self.string_plaintext_label = QtWidgets.QLabel(self.str_tab)
        self.string_plaintext_label.setGeometry(QtCore.QRect(29, 50, 51, 31))
        self.string_plaintext_label.setObjectName("plaintext_label_2")
        self.string_key_input = QtWidgets.QLineEdit(self.str_tab)
        self.string_key_input.setGeometry(QtCore.QRect(110, 10, 391, 31))
        self.string_key_input.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.string_key_input.setClearButtonEnabled(False)
        self.string_key_input.setObjectName("input_key_2")
        self.string_import_plaintext_button = QtWidgets.QPushButton(self.str_tab)
        self.string_import_plaintext_button.setGeometry(QtCore.QRect(189, 50, 61, 31))
        self.string_import_plaintext_button.setObjectName("import_plaintext_button_2")
        self.string_show_key_checkbox = QtWidgets.QCheckBox(self.str_tab)
        self.string_show_key_checkbox.setGeometry(QtCore.QRect(410, 16, 91, 20))
        self.string_show_key_checkbox.setObjectName("check_key_2")
        self.string_cipher_text_edit = QtWidgets.QPlainTextEdit(self.str_tab)
        self.string_cipher_text_edit.setGeometry(QtCore.QRect(329, 90, 241, 381))
        self.string_cipher_text_edit.setFrameShape(QtWidgets.QFrame.Box)
        self.string_cipher_text_edit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.string_cipher_text_edit.setObjectName("cipher_text_edit_2")
        self.string_progress_bar = QtWidgets.QProgressBar(self.str_tab)
        self.string_progress_bar.setGeometry(QtCore.QRect(20, 480, 551, 23))
        self.string_progress_bar.setProperty("value", 24)
        self.string_progress_bar.setObjectName("progress_bar_2")
        self.string_decrypt_button = QtWidgets.QPushButton(self.str_tab)
        self.string_decrypt_button.setGeometry(QtCore.QRect(259, 340, 61, 31))
        self.string_decrypt_button.setObjectName("decrypt_button_2")
        self.string_input_label = QtWidgets.QLabel(self.str_tab)
        self.string_input_label.setGeometry(QtCore.QRect(20, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.string_input_label.setFont(font)
        self.string_input_label.setTextFormat(QtCore.Qt.AutoText)
        self.string_input_label.setWordWrap(False)
        self.string_input_label.setObjectName("input_label_2")
        self.string_plain_text_edit = QtWidgets.QPlainTextEdit(self.str_tab)
        self.string_plain_text_edit.setGeometry(QtCore.QRect(19, 90, 231, 381))
        self.string_plain_text_edit.setFrameShape(QtWidgets.QFrame.Box)
        self.string_plain_text_edit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.string_plain_text_edit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.string_plain_text_edit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.string_plain_text_edit.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.string_plain_text_edit.setObjectName("plain_text_edit_2")
        self.string_ciphertext_label = QtWidgets.QLabel(self.str_tab)
        self.string_ciphertext_label.setGeometry(QtCore.QRect(339, 50, 51, 31))
        self.string_ciphertext_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.string_ciphertext_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.string_ciphertext_label.setObjectName("ciphertext_label_2")
        self.string_arrow_left = QtWidgets.QLabel(self.str_tab)
        self.string_arrow_left.setGeometry(QtCore.QRect(250, 300, 81, 20))
        self.string_arrow_left.setObjectName("arrow_left_2")
        self.string_export_ciphertext_button = QtWidgets.QPushButton(self.str_tab)
        self.string_export_ciphertext_button.setGeometry(QtCore.QRect(509, 50, 61, 31))
        self.string_export_ciphertext_button.setObjectName("export_ciphertext_button_2")
        self.string_encrypt_button = QtWidgets.QPushButton(self.str_tab)
        self.string_encrypt_button.setGeometry(QtCore.QRect(261, 200, 61, 31))
        self.string_encrypt_button.setObjectName("encrypt_button_2")
        self.string_arrow_right = QtWidgets.QLabel(self.str_tab)
        self.string_arrow_right.setGeometry(QtCore.QRect(250, 250, 81, 20))
        self.string_arrow_right.setObjectName("arrow_right_2")
        self.current_cipher_label = QtWidgets.QLabel(self.str_tab)
        self.current_cipher_label.setGeometry(QtCore.QRect(251, 269, 81, 31))
        self.current_cipher_label.setAlignment(QtCore.Qt.AlignCenter)
        self.current_cipher_label.setWordWrap(True)
        self.current_cipher_label.setIndent(-1)
        self.current_cipher_label.setOpenExternalLinks(False)
        self.current_cipher_label.setObjectName("current_cipher_label")
        self.switch_mode_with_key_tabwidget.addTab(self.str_tab, "")
        self.file_tab = QtWidgets.QWidget()
        self.file_tab.setObjectName("file_tab")
        self.file_show_key_checkbox = QtWidgets.QCheckBox(self.file_tab)
        self.file_show_key_checkbox.setGeometry(QtCore.QRect(410, 16, 91, 20))
        self.file_show_key_checkbox.setObjectName("check_key_3")
        self.file_ie_key_tool_button = QtWidgets.QToolButton(self.file_tab)
        self.file_ie_key_tool_button.setGeometry(QtCore.QRect(510, 10, 61, 31))
        self.file_ie_key_tool_button.setObjectName("ie_key_tool_button_3")
        self.file_input_label = QtWidgets.QLabel(self.file_tab)
        self.file_input_label.setGeometry(QtCore.QRect(20, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.file_input_label.setFont(font)
        self.file_input_label.setTextFormat(QtCore.Qt.AutoText)
        self.file_input_label.setWordWrap(False)
        self.file_input_label.setObjectName("input_label_3")
        self.file_key_input = QtWidgets.QLineEdit(self.file_tab)
        self.file_key_input.setGeometry(QtCore.QRect(110, 10, 391, 31))
        self.file_key_input.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.file_key_input.setClearButtonEnabled(False)
        self.file_key_input.setObjectName("input_key_3")
        self.file_progress_bar = QtWidgets.QProgressBar(self.file_tab)
        self.file_progress_bar.setGeometry(QtCore.QRect(20, 480, 551, 23))
        self.file_progress_bar.setProperty("value", 24)
        self.file_progress_bar.setObjectName("progress_bar_3")
        self.file_algorithm_label = QtWidgets.QLabel(self.file_tab)
        self.file_algorithm_label.setGeometry(QtCore.QRect(250, 240, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.file_algorithm_label.setFont(font)
        self.file_algorithm_label.setAlignment(QtCore.Qt.AlignCenter)
        self.file_algorithm_label.setObjectName("what_algorithm")
        self.layoutWidget = QtWidgets.QWidget(self.file_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(22, 275, 551, 201))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.file_decrypt_button = QtWidgets.QPushButton(self.layoutWidget)
        self.file_decrypt_button.setObjectName("decrypt_button_3")
        self.gridLayout_2.addWidget(self.file_decrypt_button, 0, 1, 1, 1)
        self.file_decrypt_input_label = QtWidgets.QLabel(self.layoutWidget)
        self.file_decrypt_input_label.setObjectName("input_filename_label_2")
        self.gridLayout_2.addWidget(self.file_decrypt_input_label, 1, 0, 1, 1)
        self.file_decrypt_input_path_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.file_decrypt_input_path_edit.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.file_decrypt_input_path_edit, 1, 1, 1, 1)
        self.file_decrypt_import_button = QtWidgets.QToolButton(self.layoutWidget)
        self.file_decrypt_import_button.setObjectName("toolButton_3")
        self.gridLayout_2.addWidget(self.file_decrypt_import_button, 1, 2, 1, 1)
        self.file_decrypt_output_label = QtWidgets.QLabel(self.layoutWidget)
        self.file_decrypt_output_label.setObjectName("save_to_label_2")
        self.gridLayout_2.addWidget(self.file_decrypt_output_label, 2, 0, 1, 1)
        self.file_decrypt_output_path_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.file_decrypt_output_path_edit.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.file_decrypt_output_path_edit, 2, 1, 1, 1)
        self.file_decrypt_output_path_button = QtWidgets.QToolButton(self.layoutWidget)
        self.file_decrypt_output_path_button.setObjectName("path_button_2")
        self.gridLayout_2.addWidget(self.file_decrypt_output_path_button, 2, 2, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.file_tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(22, 52, 551, 201))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.file_encrypt_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.file_encrypt_button.setObjectName("encrypt_button_3")
        self.gridLayout.addWidget(self.file_encrypt_button, 0, 1, 1, 1)
        self.file_encrypt_input_label = QtWidgets.QLabel(self.layoutWidget1)
        self.file_encrypt_input_label.setObjectName("input_filename_label")
        self.gridLayout.addWidget(self.file_encrypt_input_label, 1, 0, 1, 1)
        self.file_encrypt_input_path_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.file_encrypt_input_path_edit.setObjectName("import_file_path_edit")
        self.gridLayout.addWidget(self.file_encrypt_input_path_edit, 1, 1, 1, 1)
        self.file_encrypt_import_button = QtWidgets.QToolButton(self.layoutWidget1)
        self.file_encrypt_import_button.setObjectName("import_file_button")
        self.gridLayout.addWidget(self.file_encrypt_import_button, 1, 2, 1, 1)
        self.file_encrypt_output_label = QtWidgets.QLabel(self.layoutWidget1)
        self.file_encrypt_output_label.setObjectName("save_to_label")
        self.gridLayout.addWidget(self.file_encrypt_output_label, 2, 0, 1, 1)
        self.file_encrypt_output_path_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.file_encrypt_output_path_edit.setObjectName("save_path_label")
        self.gridLayout.addWidget(self.file_encrypt_output_path_edit, 2, 1, 1, 1)
        self.file_encrypt_output_path_button = QtWidgets.QToolButton(self.layoutWidget1)
        self.file_encrypt_output_path_button.setObjectName("path_button")
        self.gridLayout.addWidget(self.file_encrypt_output_path_button, 2, 2, 1, 1)
        self.layoutWidget.raise_()
        self.file_ie_key_tool_button.raise_()
        self.file_input_label.raise_()
        self.file_key_input.raise_()
        self.file_show_key_checkbox.raise_()
        self.file_progress_bar.raise_()
        self.layoutWidget.raise_()
        self.file_algorithm_label.raise_()
        self.switch_mode_with_key_tabwidget.addTab(self.file_tab, "")
        self.switch_mode_without_key_tabwidget = QtWidgets.QTabWidget(self.single)
        self.switch_mode_without_key_tabwidget.setEnabled(True)
        self.switch_mode_without_key_tabwidget.setGeometry(QtCore.QRect(170, 9, 591, 541))
        self.switch_mode_without_key_tabwidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.switch_mode_without_key_tabwidget.setAcceptDrops(False)
        self.switch_mode_without_key_tabwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.switch_mode_without_key_tabwidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.switch_mode_without_key_tabwidget.setObjectName("switch_mode_without_key_tabwidget")
        self.str_tab_3 = QtWidgets.QWidget()
        self.str_tab_3.setObjectName("str_tab_3")
        self.public_plaintext_label = QtWidgets.QLabel(self.str_tab_3)
        self.public_plaintext_label.setGeometry(QtCore.QRect(29, 50, 51, 31))
        self.public_plaintext_label.setObjectName("plaintext_label_4")
        self.public_import_plaintext_button = QtWidgets.QPushButton(self.str_tab_3)
        self.public_import_plaintext_button.setGeometry(QtCore.QRect(189, 50, 61, 31))
        self.public_import_plaintext_button.setObjectName("import_plaintext_button_4")
        self.public_cipher_text_edit = QtWidgets.QPlainTextEdit(self.str_tab_3)
        self.public_cipher_text_edit.setGeometry(QtCore.QRect(329, 90, 241, 381))
        self.public_cipher_text_edit.setFrameShape(QtWidgets.QFrame.Box)
        self.public_cipher_text_edit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.public_cipher_text_edit.setObjectName("cipher_text_edit_4")
        self.public_progress_bar = QtWidgets.QProgressBar(self.str_tab_3)
        self.public_progress_bar.setGeometry(QtCore.QRect(20, 480, 551, 23))
        self.public_progress_bar.setProperty("value", 24)
        self.public_progress_bar.setObjectName("progress_bar_6")
        self.public_decrypt_button = QtWidgets.QPushButton(self.str_tab_3)
        self.public_decrypt_button.setGeometry(QtCore.QRect(259, 340, 61, 31))
        self.public_decrypt_button.setObjectName("decrypt_button_6")
        self.public_plain_text_edit = QtWidgets.QPlainTextEdit(self.str_tab_3)
        self.public_plain_text_edit.setGeometry(QtCore.QRect(19, 90, 231, 381))
        self.public_plain_text_edit.setFrameShape(QtWidgets.QFrame.Box)
        self.public_plain_text_edit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.public_plain_text_edit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.public_plain_text_edit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.public_plain_text_edit.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.public_plain_text_edit.setObjectName("plain_text_edit_4")
        self.public_ciphertext_label = QtWidgets.QLabel(self.str_tab_3)
        self.public_ciphertext_label.setGeometry(QtCore.QRect(339, 50, 51, 31))
        self.public_ciphertext_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.public_ciphertext_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.public_ciphertext_label.setObjectName("ciphertext_label_4")
        self.public_arrow_left = QtWidgets.QLabel(self.str_tab_3)
        self.public_arrow_left.setGeometry(QtCore.QRect(250, 300, 81, 20))
        self.public_arrow_left.setObjectName("arrow_left_4")
        self.public_export_ciphertext_button = QtWidgets.QPushButton(self.str_tab_3)
        self.public_export_ciphertext_button.setGeometry(QtCore.QRect(509, 50, 61, 31))
        self.public_export_ciphertext_button.setObjectName("export_ciphertext_button_4")
        self.public_encrypt_button = QtWidgets.QPushButton(self.str_tab_3)
        self.public_encrypt_button.setGeometry(QtCore.QRect(261, 200, 61, 31))
        self.public_encrypt_button.setObjectName("encrypt_button_6")
        self.public_arrow_right = QtWidgets.QLabel(self.str_tab_3)
        self.public_arrow_right.setGeometry(QtCore.QRect(250, 250, 81, 20))
        self.public_arrow_right.setObjectName("arrow_right_4")
        self.public_current_cipher_label = QtWidgets.QLabel(self.str_tab_3)
        self.public_current_cipher_label.setGeometry(QtCore.QRect(251, 269, 81, 31))
        self.public_current_cipher_label.setAlignment(QtCore.Qt.AlignCenter)
        self.public_current_cipher_label.setWordWrap(True)
        self.public_current_cipher_label.setIndent(-1)
        self.public_current_cipher_label.setOpenExternalLinks(False)
        self.public_current_cipher_label.setObjectName("current_cipher_label_3")
        self.public_generate_keypair_button = QtWidgets.QPushButton(self.str_tab_3)
        self.public_generate_keypair_button.setGeometry(QtCore.QRect(20, 10, 93, 31))
        self.public_generate_keypair_button.setObjectName("generate_keypair_button")
        self.public_private_key_display = QtWidgets.QTextBrowser(self.str_tab_3)
        self.public_private_key_display.setGeometry(QtCore.QRect(120, 10, 381, 31))
        self.public_private_key_display.setObjectName("show_keypair_text")
        self.public_export_keypair_tool_button = QtWidgets.QToolButton(self.str_tab_3)
        self.public_export_keypair_tool_button.setGeometry(QtCore.QRect(510, 10, 61, 31))
        self.public_export_keypair_tool_button.setObjectName("export_keypair_toolButton")
        self.switch_mode_without_key_tabwidget.addTab(self.str_tab_3, "")
        self.file_tab_3 = QtWidgets.QWidget()
        self.file_tab_3.setObjectName("file_tab_3")
        self.progress_bar_7 = QtWidgets.QProgressBar(self.file_tab_3)
        self.progress_bar_7.setGeometry(QtCore.QRect(20, 480, 551, 23))
        self.progress_bar_7.setProperty("value", 24)
        self.progress_bar_7.setObjectName("progress_bar_7")
        self.layoutWidget_2 = QtWidgets.QWidget(self.file_tab_3)
        self.layoutWidget_2.setGeometry(QtCore.QRect(21, 51, 551, 421))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.public_file_encrypt_button = QtWidgets.QPushButton(self.layoutWidget_2)
        self.public_file_encrypt_button.setObjectName("encrypt_button_7")
        self.gridLayout_5.addWidget(self.public_file_encrypt_button, 0, 1, 1, 1)
        self.public_file_encrypt_input_label = QtWidgets.QLabel(self.layoutWidget_2)
        self.public_file_encrypt_input_label.setObjectName("input_filename_label_5")
        self.gridLayout_5.addWidget(self.public_file_encrypt_input_label, 1, 0, 1, 1)
        self.public_file_encrypt_input_path_edit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.public_file_encrypt_input_path_edit.setObjectName("import_file_path_edit_3")
        self.gridLayout_5.addWidget(self.public_file_encrypt_input_path_edit, 1, 1, 1, 1)
        self.public_file_encrypt_import_button = QtWidgets.QToolButton(self.layoutWidget_2)
        self.public_file_encrypt_import_button.setObjectName("import_file_button_3")
        self.gridLayout_5.addWidget(self.public_file_encrypt_import_button, 1, 2, 1, 1)
        self.public_file_encrypt_output_label = QtWidgets.QLabel(self.layoutWidget_2)
        self.public_file_encrypt_output_label.setObjectName("save_to_label_5")
        self.gridLayout_5.addWidget(self.public_file_encrypt_output_label, 2, 0, 1, 1)
        self.public_file_encrypt_output_path_edit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.public_file_encrypt_output_path_edit.setObjectName("save_path_label_3")
        self.gridLayout_5.addWidget(self.public_file_encrypt_output_path_edit, 2, 1, 1, 1)
        self.public_file_encrypt_output_path_button = QtWidgets.QToolButton(self.layoutWidget_2)
        self.public_file_encrypt_output_path_button.setObjectName("path_button_5")
        self.gridLayout_5.addWidget(self.public_file_encrypt_output_path_button, 2, 2, 1, 1)
        self.verticalLayout_12.addLayout(self.gridLayout_5)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.public_file_decrypt_button = QtWidgets.QPushButton(self.layoutWidget_2)
        self.public_file_decrypt_button.setObjectName("decrypt_button_7")
        self.gridLayout_6.addWidget(self.public_file_decrypt_button, 0, 1, 1, 1)
        self.public_file_decrypt_input_label = QtWidgets.QLabel(self.layoutWidget_2)
        self.public_file_decrypt_input_label.setObjectName("input_filename_label_6")
        self.gridLayout_6.addWidget(self.public_file_decrypt_input_label, 1, 0, 1, 1)
        self.public_file_decrypt_input_path_edit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.public_file_decrypt_input_path_edit.setObjectName("lineEdit_7")
        self.gridLayout_6.addWidget(self.public_file_decrypt_input_path_edit, 1, 1, 1, 1)
        self.public_file_decrypt_import_button = QtWidgets.QToolButton(self.layoutWidget_2)
        self.public_file_decrypt_import_button.setObjectName("toolButton_5")
        self.gridLayout_6.addWidget(self.public_file_decrypt_import_button, 1, 2, 1, 1)
        self.public_file_decrypt_output_label = QtWidgets.QLabel(self.layoutWidget_2)
        self.public_file_decrypt_output_label.setObjectName("save_to_label_6")
        self.gridLayout_6.addWidget(self.public_file_decrypt_output_label, 2, 0, 1, 1)
        self.public_file_decrypt_output_path_edit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.public_file_decrypt_output_path_edit.setObjectName("lineEdit_8")
        self.gridLayout_6.addWidget(self.public_file_decrypt_output_path_edit, 2, 1, 1, 1)
        self.public_file_decrypt_output_path_button = QtWidgets.QToolButton(self.layoutWidget_2)
        self.public_file_decrypt_output_path_button.setObjectName("path_button_6")
        self.gridLayout_6.addWidget(self.public_file_decrypt_output_path_button, 2, 2, 1, 1)
        self.verticalLayout_12.addLayout(self.gridLayout_6)
        self.public_file_algorithm_label = QtWidgets.QLabel(self.file_tab_3)
        self.public_file_algorithm_label.setGeometry(QtCore.QRect(250, 240, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.public_file_algorithm_label.setFont(font)
        self.public_file_algorithm_label.setAlignment(QtCore.Qt.AlignCenter)
        self.public_file_algorithm_label.setObjectName("what_algorithm_2")
        self.public_file_generate_keypair_button = QtWidgets.QPushButton(self.file_tab_3)
        self.public_file_generate_keypair_button.setGeometry(QtCore.QRect(20, 10, 93, 31))
        self.public_file_generate_keypair_button.setObjectName("generate_keypair_button_2")
        self.public_file_private_key_display = QtWidgets.QTextBrowser(self.file_tab_3)
        self.public_file_private_key_display.setGeometry(QtCore.QRect(120, 10, 381, 31))
        self.public_file_private_key_display.setObjectName("show_keypair_text_2")
        self.public_file_export_keypair_tool_button = QtWidgets.QToolButton(self.file_tab_3)
        self.public_file_export_keypair_tool_button.setGeometry(QtCore.QRect(510, 10, 61, 31))
        self.public_file_export_keypair_tool_button.setObjectName("export_keypair_toolButton_2")
        self.switch_mode_without_key_tabwidget.addTab(self.file_tab_3, "")
        self.md5_frame = QtWidgets.QFrame(self.single)
        self.md5_frame.setGeometry(QtCore.QRect(170, 10, 591, 541))
        self.md5_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.md5_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.md5_frame.setObjectName("md5_frame")
        self.md5_show_text = QtWidgets.QTextBrowser(self.md5_frame)
        self.md5_show_text.setGeometry(QtCore.QRect(20, 440, 551, 31))
        self.md5_show_text.setObjectName("md5_show_text")
        self.lineEdit = QtWidgets.QLineEdit(self.md5_frame)
        self.lineEdit.setGeometry(QtCore.QRect(100, 20, 391, 31))
        self.lineEdit.setObjectName("lineEdit")
        # 导入文件标签（原名 daoruwenjian_label）
        self.import_file_label = QtWidgets.QLabel(self.md5_frame)
        self.import_file_label.setGeometry(QtCore.QRect(20, 20, 81, 31))
        self.import_file_label.setObjectName("import_file_label")
        self.import_file_toolbox = QtWidgets.QToolButton(self.md5_frame)
        self.import_file_toolbox.setGeometry(QtCore.QRect(500, 20, 71, 31))
        self.import_file_toolbox.setObjectName("import_file_toolbox")
        self.progressBar = QtWidgets.QProgressBar(self.md5_frame)
        self.progressBar.setGeometry(QtCore.QRect(20, 490, 551, 31))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.md5_label = QtWidgets.QLabel(self.md5_frame)
        self.md5_label.setGeometry(QtCore.QRect(20, 400, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.md5_label.setFont(font)
        self.md5_label.setObjectName("md5_label")
        # 输入字符串标签（原名 shuruzifuchuan_label）
        self.input_string_label = QtWidgets.QLabel(self.md5_frame)
        self.input_string_label.setGeometry(QtCore.QRect(20, 60, 91, 31))
        self.input_string_label.setObjectName("input_string_label")
        self.layoutWidget2 = QtWidgets.QWidget(self.md5_frame)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 100, 551, 291))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.input_edit = QtWidgets.QPlainTextEdit(self.layoutWidget2)
        self.input_edit.setObjectName("input_edit")
        self.verticalLayout_13.addWidget(self.input_edit)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_13.addWidget(self.pushButton)
        self.base_frame = QtWidgets.QFrame(self.single)
        self.base_frame.setGeometry(QtCore.QRect(169, 9, 591, 541))
        self.base_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.base_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.base_frame.setObjectName("base_frame")
        self.base_frame.raise_()
        self.cipher_switch_toolbox.raise_()
        self.cipher_with_key_frame.raise_()
        self.md5_frame.raise_()
        self.switch_mode_without_key_tabwidget.raise_()
        self.switch_mode_with_key_tabwidget.raise_()
        self.switch_sd.addWidget(self.single)
        self.dual = QtWidgets.QWidget()
        self.dual.setObjectName("dual")
        self.switch_sd.addWidget(self.dual)
        main_window.setCentralWidget(self.centralwidget)

        # 初始化状态栏
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)

        # 面板初始可见性设置
        self._initialize_visibility()

        # 初始化输入限制与校验器
        self._setup_validators()

        # 初始化密钥导入/导出菜单
        self._setup_menus()

        # 流密码+分组密码校验器
        self.string_key_input.setEchoMode(QLineEdit.Password)
        self.file_key_input.setEchoMode(QLineEdit.Password)
        self.string_key_validator_alnum = QRegExpValidator(self.regx, self.string_key_input)
        self.file_key_validator_alnum = QRegExpValidator(self.regx, self.file_key_input)
        self.string_key_validator_numeric = QRegExpValidator(self.regx_2, self.string_key_input)
        self.file_key_validator_numeric = QRegExpValidator(self.regx_2, self.file_key_input)

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "单机加解密"))
        self.caesar.setText(_translate("MainWindow", "凯撒密码"))
        self.keyword.setText(_translate("MainWindow", "关键字密码"))
        self.affine.setText(_translate("MainWindow", "仿射密码"))
        self.multilateral.setText(_translate("MainWindow", "多边密码"))
        self.classical_cipher_switch.setItemText(self.classical_cipher_switch.indexOf(self.single_substitution_page),
                                                 _translate("MainWindow", "单表替代密码"))
        self.vigenere.setText(_translate("MainWindow", "维吉尼亚密码"))
        self.autokey_ciphertext.setText(_translate("MainWindow", "Autokey密文"))
        self.autokey_plaintext.setText(_translate("MainWindow", "Autokey明文"))
        self.classical_cipher_switch.setItemText(self.classical_cipher_switch.indexOf(self.multiple_substitution_page),
                                                 _translate("MainWindow", "多表替代密码"))
        self.playfair.setText(_translate("MainWindow", "波雷费密码"))
        self.classical_cipher_switch.setItemText(self.classical_cipher_switch.indexOf(self.polygraph_substitution_page),
                                                 _translate("MainWindow", "多图替代密码"))
        self.permutation.setText(_translate("MainWindow", "置换密码"))
        self.column_permutation.setText(_translate("MainWindow", "列置换密码"))
        self.double_transposition.setText(_translate("MainWindow", "双重置换密码"))
        self.classical_cipher_switch.setItemText(self.classical_cipher_switch.indexOf(self.transposition_page),
                                                 _translate("MainWindow", "置换密码"))
        self.cipher_switch_toolbox.setItemText(self.cipher_switch_toolbox.indexOf(self.classical_cipher_page),
                                               _translate("MainWindow", "古典密码"))
        self.RC4.setText(_translate("MainWindow", "RC4"))
        self.CA.setText(_translate("MainWindow", "CA"))
        self.cipher_switch_toolbox.setItemText(self.cipher_switch_toolbox.indexOf(self.stream_cipher_page),
                                               _translate("MainWindow", "流密码"))
        self.DES.setText(_translate("MainWindow", "DES"))
        self.AES.setText(_translate("MainWindow", "AES"))
        self.cipher_switch_toolbox.setItemText(self.cipher_switch_toolbox.indexOf(self.block_cipher_page),
                                               _translate("MainWindow", "分组密码"))
        self.RSA.setText(_translate("MainWindow", "RSA"))
        self.ECC.setText(_translate("MainWindow", "ECC"))
        self.cipher_switch_toolbox.setItemText(self.cipher_switch_toolbox.indexOf(self.public_key_page),
                                               _translate("MainWindow", "公钥密码"))
        self.MD5.setText(_translate("MainWindow", "MD5"))
        self.cipher_switch_toolbox.setItemText(self.cipher_switch_toolbox.indexOf(self.hash_page),
                                               _translate("MainWindow", "单向散列函数"))
        self.cipher_switch_toolbox.setItemText(self.cipher_switch_toolbox.indexOf(self.about_page),
                                               _translate("MainWindow", "关于"))
        self.input_label.setText(_translate("MainWindow", "请输入密钥："))
        self.ie_key_tool_button.setText(_translate("MainWindow", "..."))
        self.plaintext_label.setText(_translate("MainWindow", "明文："))
        self.import_plaintext_button.setText(_translate("MainWindow", "导入"))
        self.export_ciphertext_button.setText(_translate("MainWindow", "导出"))
        self.ciphertext_label.setText(_translate("MainWindow", "密文："))
        self.encrypt_button.setText(_translate("MainWindow", "加密"))
        self.decrypt_button.setText(_translate("MainWindow", "解密"))
        self.arrow_right.setText(_translate("MainWindow", "-------->>"))
        self.arrow_left.setText(_translate("MainWindow", "<<--------"))
        self.check_key.setText(_translate("MainWindow", "显示密钥"))
        self.label.setText(_translate("MainWindow", "凯撒密码"))
        self.string_ie_key_tool_button.setText(_translate("MainWindow", "..."))
        self.string_plaintext_label.setText(_translate("MainWindow", "明文："))
        self.string_import_plaintext_button.setText(_translate("MainWindow", "导入"))
        self.string_show_key_checkbox.setText(_translate("MainWindow", "显示密钥"))
        self.string_decrypt_button.setText(_translate("MainWindow", "解密"))
        self.string_input_label.setText(_translate("MainWindow", "请输入密钥："))
        self.string_ciphertext_label.setText(_translate("MainWindow", "密文："))
        self.string_arrow_left.setText(_translate("MainWindow", "<<--------"))
        self.string_export_ciphertext_button.setText(_translate("MainWindow", "导出"))
        self.string_encrypt_button.setText(_translate("MainWindow", "加密"))
        self.string_arrow_right.setText(_translate("MainWindow", "-------->>"))
        self.current_cipher_label.setText(_translate("MainWindow", "DES"))
        self.switch_mode_with_key_tabwidget.setTabText(self.switch_mode_with_key_tabwidget.indexOf(self.str_tab),
                                                       _translate("MainWindow", "字符串加解密"))
        self.file_show_key_checkbox.setText(_translate("MainWindow", "显示密钥"))
        self.file_ie_key_tool_button.setText(_translate("MainWindow", "..."))
        self.file_input_label.setText(_translate("MainWindow", "请输入密钥："))
        self.file_algorithm_label.setText(_translate("MainWindow", "RC4"))
        self.file_decrypt_button.setText(_translate("MainWindow", "解密"))
        self.file_decrypt_input_label.setText(_translate("MainWindow", "导入文件："))
        self.file_decrypt_import_button.setText(_translate("MainWindow", "..."))
        self.file_decrypt_output_label.setText(_translate("MainWindow", "保存至："))
        self.file_decrypt_output_path_button.setText(_translate("MainWindow", "..."))
        self.file_encrypt_button.setText(_translate("MainWindow", "加密"))
        self.file_encrypt_input_label.setText(_translate("MainWindow", "导入文件："))
        self.file_encrypt_import_button.setText(_translate("MainWindow", "..."))
        self.file_encrypt_output_label.setText(_translate("MainWindow", "保存至："))
        self.file_encrypt_output_path_button.setText(_translate("MainWindow", "..."))
        self.switch_mode_with_key_tabwidget.setTabText(self.switch_mode_with_key_tabwidget.indexOf(self.file_tab),
                                                       _translate("MainWindow", "文件加解密"))
        self.public_plaintext_label.setText(_translate("MainWindow", "明文："))
        self.public_import_plaintext_button.setText(_translate("MainWindow", "导入"))
        self.public_decrypt_button.setText(_translate("MainWindow", "解密"))
        self.public_ciphertext_label.setText(_translate("MainWindow", "密文："))
        self.public_arrow_left.setText(_translate("MainWindow", "<<--------"))
        self.public_export_ciphertext_button.setText(_translate("MainWindow", "导出"))
        self.public_encrypt_button.setText(_translate("MainWindow", "加密"))
        self.public_arrow_right.setText(_translate("MainWindow", "-------->>"))
        self.public_current_cipher_label.setText(_translate("MainWindow", "RSA"))
        self.public_generate_keypair_button.setText(_translate("MainWindow", "生成密钥对"))
        self.public_export_keypair_tool_button.setText(_translate("MainWindow", "..."))
        self.switch_mode_without_key_tabwidget.setTabText(
            self.switch_mode_without_key_tabwidget.indexOf(self.str_tab_3), _translate("MainWindow", "字符串加解密"))
        self.public_file_encrypt_button.setText(_translate("MainWindow", "加密"))
        self.public_file_encrypt_input_label.setText(_translate("MainWindow", "导入文件："))
        self.public_file_encrypt_import_button.setText(_translate("MainWindow", "..."))
        self.public_file_encrypt_output_label.setText(_translate("MainWindow", "保存至："))
        self.public_file_encrypt_output_path_button.setText(_translate("MainWindow", "..."))
        self.public_file_decrypt_button.setText(_translate("MainWindow", "解密"))
        self.public_file_decrypt_input_label.setText(_translate("MainWindow", "导入文件："))
        self.public_file_decrypt_import_button.setText(_translate("MainWindow", "..."))
        self.public_file_decrypt_output_label.setText(_translate("MainWindow", "保存至："))
        self.public_file_decrypt_output_path_button.setText(_translate("MainWindow", "..."))
        self.public_file_algorithm_label.setText(_translate("MainWindow", "RC4"))
        self.public_file_generate_keypair_button.setText(_translate("MainWindow", "生成密钥对"))
        self.public_file_export_keypair_tool_button.setText(_translate("MainWindow", "..."))
        self.switch_mode_without_key_tabwidget.setTabText(
            self.switch_mode_without_key_tabwidget.indexOf(self.file_tab_3), _translate("MainWindow", "文件加解密"))
        self.import_file_label.setText(_translate("MainWindow", "导入文件："))
        self.import_file_toolbox.setText(_translate("MainWindow", "..."))
        self.md5_label.setText(_translate("MainWindow", "MD5："))
        self.input_string_label.setText(_translate("MainWindow", "输入字符串："))
        self.pushButton.setText(_translate("MainWindow", "生成MD5"))

    def _initialize_visibility(self):
        """
        统一管理各主面板初始可见性，避免散落在 UI 构建代码中。
        """
        self.base_frame.setVisible(True)
        self.cipher_with_key_frame.setVisible(False)
        self.switch_mode_with_key_tabwidget.setVisible(False)
        self.switch_mode_without_key_tabwidget.setVisible(False)
        self.md5_frame.setVisible(False)

    def _setup_validators(self):
        """
        初始化正则与输入校验器，保证各类密钥输入遵循既定约束。
        """
        # 初始化正则表达式：仅能输入大小写字母和数字
        self.regx = QRegExp("[a-zA-Z0-9]+$")
        self.regx_2 = QRegExp("[0-9]+$")
        self.regx_3 = QRegExp("[a-zA-Z]+$")
        self.regx_4 = QRegExp("[0-9 ]+$")
        self.regx_5 = QRegExp("[a-zA-Z ]+$")

        # 古典密码部件设置
        self.input_key.setEchoMode(QLineEdit.Password)
        self.classical_key_validator_alnum = QRegExpValidator(self.regx, self.input_key)
        self.classical_key_validator_numeric = QRegExpValidator(self.regx_2, self.input_key)
        self.classical_key_validator_alpha = QRegExpValidator(self.regx_3, self.input_key)
        self.classical_key_validator_numeric_space = QRegExpValidator(self.regx_4, self.input_key)
        self.classical_key_validator_alpha_space = QRegExpValidator(self.regx_5, self.input_key)

    def _setup_menus(self):
        """
        构建导入/导出菜单并绑定到对应的工具按钮，避免在主方法中混杂细节。
        """
        self.ie_menu_1 = QMenu()
        self.ie_menu_1.addAction("导入", self.import_1)
        self.ie_menu_1.addAction("导出", self.export_1)

        self.ie_menu_2 = QMenu()
        self.ie_menu_2.addAction("导入", self.import_2)
        self.ie_menu_2.addAction("导出", self.export_2)

        self.ie_menu_3 = QMenu()
        self.ie_menu_3.addAction("导入", self.import_3)
        self.ie_menu_3.addAction("导出", self.export_3)

        self.ie_menu_4 = QMenu()
        self.ie_menu_4.addAction("导入公私钥", self.import_4)
        self.ie_menu_4.addAction("导出私钥", self.export_4)

        self.ie_key_tool_button.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.ie_key_tool_button.setMenu(self.ie_menu_1)

        self.string_ie_key_tool_button.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.string_ie_key_tool_button.setMenu(self.ie_menu_2)

        self.file_ie_key_tool_button.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.file_ie_key_tool_button.setMenu(self.ie_menu_3)

        self.public_export_keypair_tool_button.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.public_export_keypair_tool_button.setMenu(self.ie_menu_4)

        self.public_file_export_keypair_tool_button.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.public_file_export_keypair_tool_button.setMenu(self.ie_menu_4)
